# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-13 23:23:43
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def inorganic_v2():  # inorganic_v2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    gebco_land_shallow_fill_dir_accum_n_tif_3_ = arcpy.Raster("gebco_land_shallow_fill_dir_accum_n.tif")
    eco_ch_shore_shoreline_proportion_norm01_1km_v01_0_tif = arcpy.Raster("eco_ch_shore_shoreline_proportion_norm01_1km_v01.0.tif")
    nutrient_input_v02_1km_tif = arcpy.Raster("nutrient_input_v02_1km.tif")
    v1_volumn_runoff_norm_int_tif = arcpy.Raster("v1_volumn_runoff_norm_int.tif")
    v1_flow_acc_pres_norm_int_tif = arcpy.Raster("v1_flow_acc_pres_norm_int.tif")
    grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
    proc = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc"
    pol_inorganic_v2_1km_tif = arcpy.Raster("pol_inorganic_v2_1km.tif")

    # Process: Focal Statistics (3) (Focal Statistics) (ia)
    flow_acc_focal_land_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_acc_focal_land.tif"
    Focal_Statistics_3_ = flow_acc_focal_land_tif
    flow_acc_focal_land_tif = arcpy.ia.FocalStatistics(in_raster=gebco_land_shallow_fill_dir_accum_n_tif_3_, neighborhood="Rectangle 50 50 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
    flow_acc_focal_land_tif.save(Focal_Statistics_3_)


    # Process: Reclassify (Reclassify) (sa)
    shorline_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\shorline_grid.tif"
    Reclassify = shorline_grid_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        shorline_grid_tif = arcpy.sa.Reclassify(in_raster=eco_ch_shore_shoreline_proportion_norm01_1km_v01_0_tif, reclass_field="VALUE", remap="0 NODATA;0,200000 1;0,400000 1;0,600000 1;0,800000 1;1 1", missing_values="DATA")
        shorline_grid_tif.save(Reclassify)


    # Process: Extract by Mask (4) (Extract by Mask) (sa)
    flow_acc_landExtarct_shore_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_acc_landExtarct_shore.tif"
    Extract_by_Mask_4_ = flow_acc_landExtarct_shore_tif
    flow_acc_landExtarct_shore_tif = arcpy.sa.ExtractByMask(in_raster=flow_acc_focal_land_tif, in_mask_data=shorline_grid_tif)
    flow_acc_landExtarct_shore_tif.save(Extract_by_Mask_4_)


    # Process: Extract by Mask (3) (Extract by Mask) (sa)
    Chla_shoreline_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\Chla_shoreline_grid.tif"
    Extract_by_Mask_3_ = Chla_shoreline_grid_tif
    Chla_shoreline_grid_tif = arcpy.sa.ExtractByMask(in_raster=nutrient_input_v02_1km_tif, in_mask_data=shorline_grid_tif)
    Chla_shoreline_grid_tif.save(Extract_by_Mask_3_)


    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    volumn_runoff_shore_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\volumn_runoff_shore.tif"
    Extract_by_Mask_2_ = volumn_runoff_shore_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        volumn_runoff_shore_tif = arcpy.sa.ExtractByMask(in_raster=v1_volumn_runoff_norm_int_tif, in_mask_data=shorline_grid_tif)
        volumn_runoff_shore_tif.save(Extract_by_Mask_2_)


    # Process: Extract by Mask (Extract by Mask) (sa)
    flow_acc_shoreline_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_acc_shoreline.tif"
    Extract_by_Mask = flow_acc_shoreline_tif
    flow_acc_shoreline_tif = arcpy.sa.ExtractByMask(in_raster=v1_flow_acc_pres_norm_int_tif, in_mask_data=shorline_grid_tif)
    flow_acc_shoreline_tif.save(Extract_by_Mask)


    # Process: Raster Calculator (Raster Calculator) (ia)
    flow_pressure_runoff_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_pressure_runoff.tif"
    Raster_Calculator = flow_pressure_runoff_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        flow_pressure_runoff_tif = flow_acc_landExtarct_shore_tif  * Chla_shoreline_grid_tif * volumn_runoff_shore_tif * flow_acc_shoreline_tif
        flow_pressure_runoff_tif.save(Raster_Calculator)


    # Process: Focal Statistics (Focal Statistics) (ia)
    flow_pressure_runoff_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_pressure_runoff_focal.tif"
    Focal_Statistics = flow_pressure_runoff_focal_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        flow_pressure_runoff_focal_tif = arcpy.ia.FocalStatistics(in_raster=flow_pressure_runoff_tif, neighborhood="Wedge 5 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
        flow_pressure_runoff_focal_tif.save(Focal_Statistics)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    flow_pressure_runoff_log_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_pressure_runoff_log.tif"
    Raster_Calculator_2_ = flow_pressure_runoff_log_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        flow_pressure_runoff_log_tif =  Log10(flow_pressure_runoff_focal_tif)
        flow_pressure_runoff_log_tif.save(Raster_Calculator_2_)


    # Process: Extract by Mask (5) (Extract by Mask) (sa)
    flow_pressure_runoff_log_shore_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_pressure_runoff_log_shore.tif"
    Extract_by_Mask_5_ = flow_pressure_runoff_log_shore_tif
    flow_pressure_runoff_log_shore_tif = arcpy.sa.ExtractByMask(in_raster=flow_pressure_runoff_focal_tif, in_mask_data=shorline_grid_tif)
    flow_pressure_runoff_log_shore_tif.save(Extract_by_Mask_5_)


    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    grid0_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\grid0.tif"
    Raster_Calculator_3_ = grid0_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        grid0_tif =  grid_1km_v01_1_tif  *0
        grid0_tif.save(Raster_Calculator_3_)


    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    flow_pres_grid0_tif = arcpy.management.MosaicToNewRaster(input_rasters=[flow_pressure_runoff_log_shore_tif, grid0_tif], output_location=proc, raster_dataset_name_with_extension="flow_pres_grid0.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    flow_pres_grid0_tif = arcpy.Raster(flow_pres_grid0_tif)

    # Process: Focal Statistics (2) (Focal Statistics) (ia)
    flow_pres_grid_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\proc\\flow_pres_grid_focal.tif"
    Focal_Statistics_2_ = flow_pres_grid_focal_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        flow_pres_grid_focal_tif = arcpy.ia.FocalStatistics(in_raster=flow_pres_grid0_tif, neighborhood="Wedge 3 0 360 CELL", statistics_type="RANGE", ignore_nodata="DATA", percentile_value=90)
        flow_pres_grid_focal_tif.save(Focal_Statistics_2_)


    # Process: Extract by Mask (6) (Extract by Mask) (sa)
    flow_pressure_v2_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\flow_pressure_v2.tif"
    Extract_by_Mask_6_ = flow_pressure_v2_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        flow_pressure_v2_tif = arcpy.sa.ExtractByMask(in_raster=flow_pres_grid_focal_tif, in_mask_data=grid_1km_v01_1_tif)
        flow_pressure_v2_tif.save(Extract_by_Mask_6_)


    # Process: Raster Calculator (4) (Raster Calculator) (ia)
    flow_pressure_log_v2_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v02\\flow_pressure_log_v2.tif"
    Raster_Calculator_4_ = flow_pressure_log_v2_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        flow_pressure_log_v2_tif =  Log10(flow_pressure_v2_tif) 
        flow_pressure_log_v2_tif.save(Raster_Calculator_4_)


    # Process: Raster Calculator (5) (Raster Calculator) (ia)
    pol_inorganicX10_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_inorg\\v02\\proc\\pol_inorganicX10.tif"
    Raster_Calculator_5_ = pol_inorganicX10_tif
    pol_inorganicX10_tif =  pol_inorganic_v2_1km_tif *10
    pol_inorganicX10_tif.save(Raster_Calculator_5_)


    # Process: Raster Calculator (6) (Raster Calculator) (ia)
    pol_inorg_v2_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_inorg\\v02\\pol_inorg_v2.tif"
    Raster_Calculator_6_ = pol_inorg_v2_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        pol_inorg_v2_tif =  pol_inorganicX10_tif/ (Int(flow_pressure_v2_tif))
        pol_inorg_v2_tif.save(Raster_Calculator_6_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\env\hydro\v02\proc\hydro_v2\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\env\hydro\v02\proc\hydro_v2\Default.gdb"):
        inorganic_v2()
