# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-07 10:32:41
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def salt_marsh_model():  # salt_marsh_model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    ndvi_mean_woi_tif = arcpy.Raster("ndvi_mean_woi.tif")
    Intertidal_areas2014_16_tif = arcpy.Raster("Intertidal_areas2014-16.tif")
    Intertidal_areas2002_04_tif = arcpy.Raster("Intertidal_areas2002-04.tif")
    Intertidal_areas2011_13_tif = arcpy.Raster("Intertidal_areas2011-13.tif")
    grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
    mangrove_proportion_tif_mangrove_proportion_tif = arcpy.Raster("ModelBuilder\\mangrove_proportion.tif:mangrove_proportion.tif")

    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    NDVI_mean_2020_value_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\NDVI_mean_2020_value.tif"
    Raster_Calculator_2_ = NDVI_mean_2020_value_tif
    NDVI_mean_2020_value_tif =  ndvi_mean_woi_tif/1000
    NDVI_mean_2020_value_tif.save(Raster_Calculator_2_)


    # Process: Project Raster (Project Raster) (management)
    NDVI_mean_2020_value_Project = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\salt_marsh\\Default.gdb\\NDVI_mean_2020_value_Project"
    arcpy.management.ProjectRaster(in_raster=NDVI_mean_2020_value_tif, out_raster=NDVI_mean_2020_value_Project, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
    NDVI_mean_2020_value_Project = arcpy.Raster(NDVI_mean_2020_value_Project)

    # Process: Raster Calculator (Raster Calculator) (ia)
    Intertidal_areas_combine_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Intertidal_areas_combine.tif"
    Raster_Calculator = Intertidal_areas_combine_tif
    Intertidal_areas_combine_tif =  Intertidal_areas2014_16_tif + Intertidal_areas2002_04_tif + Intertidal_areas2011_13_tif
    Intertidal_areas_combine_tif.save(Raster_Calculator)


    # Process: Project Raster (2) (Project Raster) (management)
    Intertidal_combine_projectRas_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Intertidal_combine_projectRas.tif"
    arcpy.management.ProjectRaster(in_raster=Intertidal_areas_combine_tif, out_raster=Intertidal_combine_projectRas_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="", vertical="NO_VERTICAL")
    Intertidal_combine_projectRas_tif = arcpy.Raster(Intertidal_combine_projectRas_tif)

    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    Intertidal_areas_combine_setnull_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Intertidal_areas_combine_setnull.tif"
    Raster_Calculator_3_ = Intertidal_areas_combine_setnull_tif
    Intertidal_areas_combine_setnull_tif =  SetNull(Intertidal_combine_projectRas_tif <=0,Intertidal_combine_projectRas_tif)
    Intertidal_areas_combine_setnull_tif.save(Raster_Calculator_3_)


    # Process: Reclassify (Reclassify) (sa)
    Intertidal_areas_combine_reclassify_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Intertidal_areas_combine_reclassify.tif"
    Reclassify = Intertidal_areas_combine_reclassify_tif
    Intertidal_areas_combine_reclassify_tif = arcpy.sa.Reclassify(in_raster=Intertidal_areas_combine_setnull_tif, reclass_field="Value", remap="1 3 1", missing_values="DATA")
    Intertidal_areas_combine_reclassify_tif.save(Reclassify)


    # Process: Extract by Mask (Extract by Mask) (sa)
    Salt_mash_extractInt_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Salt_mash_extractInt.tif"
    Extract_by_Mask = Salt_mash_extractInt_tif
    Salt_mash_extractInt_tif = arcpy.sa.ExtractByMask(in_raster=NDVI_mean_2020_value_Project, in_mask_data=Intertidal_areas_combine_reclassify_tif)
    Salt_mash_extractInt_tif.save(Extract_by_Mask)


    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    Salt_mash_extractInt_1km_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\Salt_mash_extractInt_1km.tif"
    Extract_by_Mask_2_ = Salt_mash_extractInt_1km_tif
    Salt_mash_extractInt_1km_tif = arcpy.sa.ExtractByMask(in_raster=Salt_mash_extractInt_tif, in_mask_data=grid_1km_v01_1_tif)
    Salt_mash_extractInt_1km_tif.save(Extract_by_Mask_2_)


    # Process: Raster Calculator (4) (Raster Calculator) (ia)
    Salt_Marsh_v1_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\Salt_Marsh_v1.tif"
    Raster_Calculator_4_ = Salt_Marsh_v1_tif
    Salt_Marsh_v1_tif = SetNull(Salt_mash_extractInt_1km_tif <=0,Salt_mash_extractInt_1km_tif )
    Salt_Marsh_v1_tif.save(Raster_Calculator_4_)


    # Process: Reclassify (2) (Reclassify) (sa)
    mangrove_0_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\mangrove_0.tif"
    Reclassify_2_ = mangrove_0_tif
    mangrove_0_tif = arcpy.sa.Reclassify(in_raster=mangrove_proportion_tif_mangrove_proportion_tif, reclass_field="Value", remap="0 1;1 NODATA", missing_values="DATA")
    mangrove_0_tif.save(Reclassify_2_)


    # Process: Extract by Mask (3) (Extract by Mask) (sa)
    salt_marsh_utan_mangrove_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\proc\\salt_marsh_utan_mangrove.tif"
    Extract_by_Mask_3_ = salt_marsh_utan_mangrove_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        salt_marsh_utan_mangrove_tif = arcpy.sa.ExtractByMask(in_raster=Salt_Marsh_v1_tif, in_mask_data=mangrove_0_tif)
        salt_marsh_utan_mangrove_tif.save(Extract_by_Mask_3_)


    # Process: Raster Calculator (5) (Raster Calculator) (ia)
    Salt_Marsh_v_0_1_0_tif = "\\\\sgu.se\\sgu\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\salt_marsh\\v01\\Salt_Marsh_v.0.1.0.tif"
    Raster_Calculator_5_ = Salt_Marsh_v_0_1_0_tif
    with arcpy.EnvManager(cellSize=salt_marsh_utan_mangrove_tif):
        Salt_Marsh_v_0_1_0_tif = (salt_marsh_utan_mangrove_tif- salt_marsh_utan_mangrove_tif.minimum)/( salt_marsh_utan_mangrove_tif.maximum- salt_marsh_utan_mangrove_tif.minimum)*100
        Salt_Marsh_v_0_1_0_tif.save(Raster_Calculator_5_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\sgu.se\sgu\prod\proj\marin\swoc\work\wiosym\data\reg\eco\salt_marsh\v01\proc\salt_marsh\Default.gdb", workspace=r"\\sgu.se\sgu\prod\proj\marin\swoc\work\wiosym\data\reg\eco\salt_marsh\v01\proc\salt_marsh\Default.gdb"):
        salt_marsh_model()
