# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-09 09:32:23
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *

def water_movement_change():  # water_movement_change

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
        proc = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc"
        WIOSym_seawall_breaker = "WIOSym_seawall_breaker"
        WIOSym_WATER_MOVEMENT_CHANGE = "WIOSym_WATER_MOVEMENT_CHANGE"
        WIOSym_Land_reclaimation_3_ = "WIOSym_Land_reclaimation"
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
        proc_3_ = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc"
        grid_0proxy_tif = arcpy.Raster("\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc\\peirs_docks\\grid_0proxy.tif")
        land_rec_5km_shp_land_rec_5km = "ModelBuilder\\land_rec_5km.shp:land_rec_5km"
        proc_2_ = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc"

        # Process: Project (4) (Project) (management)
        seawall_wave_breaker_project_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\seawall_wave_breaker_project.shp"
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.management.Project(in_dataset=WIOSym_seawall_breaker, out_dataset=seawall_wave_breaker_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_EASE-Grid_2.0_Global\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",30.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (3) (Buffer) (analysis)
        seawall_5km_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\seawall_5km.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.analysis.Buffer(in_features=seawall_wave_breaker_project_shp, out_feature_class=seawall_5km_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Project (3) (Project) (management)
        land_rec_project_shp_2_ = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_project.shp"
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.management.Project(in_dataset=WIOSym_WATER_MOVEMENT_CHANGE, out_dataset=land_rec_project_shp_2_, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_EASE-Grid_2.0_Global\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",30.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (2) (Buffer) (analysis)
        water_movement_change_buffer_5km_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_change_buffer_5km.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.analysis.Buffer(in_features=land_rec_project_shp_2_, out_feature_class=water_movement_change_buffer_5km_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Project (2) (Project) (management)
        land_rec_project_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_project.shp"
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.management.Project(in_dataset=WIOSym_Land_reclaimation_3_, out_dataset=land_rec_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_EASE-Grid_2.0_Global\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",30.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (Buffer) (analysis)
        land_rec_5km_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_5km.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            arcpy.analysis.Buffer(in_features=land_rec_project_shp, out_feature_class=land_rec_5km_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Merge (Merge) (management)
        water_movement_change_combine_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_change_combine.shp"
        arcpy.management.Merge(inputs=[seawall_5km_shp, water_movement_change_buffer_5km_shp, land_rec_5km_shp], output=water_movement_change_combine_shp, field_mappings="Id \"Id\" true true false 6 Long 0 6,First,#,\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\seawall_5km.shp,Id,-1,-1,\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_change_buffer_5km.shp,Id,-1,-1,\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_5km.shp,Id,-1,-1", add_source="NO_SOURCE_INFO")

        # Process: Dissolve (Dissolve) (management)
        water_movement_change_combin = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc\\peirs_docks\\Default.gdb\\water_movement_change_combin"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
            arcpy.management.Dissolve(in_features=water_movement_change_combine_shp, out_feature_class=water_movement_change_combin, dissolve_field=["Id"], statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

        # Process: Polygon to Raster (Polygon to Raster) (conversion)
        water_movement_change_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_change.tif"
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            arcpy.conversion.PolygonToRaster(in_features=water_movement_change_combin, value_field="OBJECTID", out_rasterdataset=water_movement_change_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="NONE", cellsize="grid_1km_v01.1.tif", build_rat="BUILD")

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        water_movement_change_x10_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_change_x10.tif"
        Raster_Calculator_2_ = water_movement_change_x10_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            water_movement_change_x10_tif = water_movement_change_tif *10
            water_movement_change_x10_tif.save(Raster_Calculator_2_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        water_mc_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[water_movement_change_x10_tif, grid_1km_v01_1_tif], output_location=proc_3_, raster_dataset_name_with_extension="water_mc_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
        water_mc_combine_grid_tif = arcpy.Raster(water_mc_combine_grid_tif)

        # Process: Extract by Mask (3) (Extract by Mask) (sa)
        water_movement_mask_grid_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\proc\\water_movement_mask_grid.tif"
        Extract_by_Mask_3_ = water_movement_mask_grid_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            water_movement_mask_grid_tif = arcpy.sa.ExtractByMask(in_raster=water_mc_combine_grid_tif, in_mask_data=grid_0proxy_tif)
            water_movement_mask_grid_tif.save(Extract_by_Mask_3_)


        # Process: Raster Calculator (5) (Raster Calculator) (ia)
        water_movement_change_norm_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\water_movement_change_norm.tif"
        Raster_Calculator_5_ = water_movement_change_norm_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            water_movement_change_norm_tif =  ((water_movement_mask_grid_tif-water_movement_mask_grid_tif.minimum)/(water_movement_mask_grid_tif.maximum- water_movement_mask_grid_tif.minimum))*100
            water_movement_change_norm_tif.save(Raster_Calculator_5_)


        # Process: Reclassify (Reclassify) (sa)
        water_movement_change_v2_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nrg_water\\v01\\water_movement_change_v2.tif"
        Reclassify = water_movement_change_v2_tif
        with arcpy.EnvManager(cellSize=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            water_movement_change_v2_tif = arcpy.sa.Reclassify(in_raster=water_movement_mask_grid_tif, reclass_field="Value", remap="1 0;1 11 1", missing_values="DATA")
            water_movement_change_v2_tif.save(Reclassify)


if __name__ == '__main__':
    water_movement_change()
