# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-12 15:38:06
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def algea_farm_v3():  # algea_farm_v3

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    seaweed_farm_reg_shp_seaweed_farm_reg = "ModelBuilder\\seaweed_farm_reg.shp:seaweed_farm_reg"
    grid_1km_v01_1_tif_2_ = arcpy.Raster("grid_1km_v01.1.tif")
    v1_flow_acc_pres_norm_int_tif = arcpy.Raster("v1_flow_acc_pres_norm_int.tif")
    proc = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc"
    Chl_a_norm_int_tif = arcpy.Raster("Chl_a_norm_int.tif")
    seaweed_farm_buffer5km_shp_seaweed_farm_buffer5km = "ModelBuilder\\seaweed_farm_buffer5km.shp:seaweed_farm_buffer5km"
    proc_3_ = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc"
    aquaculture_eutro_relativ_tif_aquaculture_eutro_relativ_tif = arcpy.Raster("ModelBuilder\\aquaculture_eutro_relativ.tif:aquaculture_eutro_relativ.tif")
    seaweed_farm_moz = "seaweed_farm_moz"
    seaweed_farm_Multipolygons = "seaweed_farm_Multipolygons"

    # Process: Polygon to Raster (2) (Polygon to Raster) (conversion)
    seaweed_farm_present_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_present.tif"
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        arcpy.conversion.PolygonToRaster(in_features=seaweed_farm_reg_shp_seaweed_farm_reg, value_field="value", out_rasterdataset=seaweed_farm_present_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="value", cellsize=grid_1km_v01_1_tif_2_, build_rat="BUILD")

    # Process: Raster to Point (Raster to Point) (conversion)
    seaweed_farm_points_presence_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_points_presence.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        arcpy.conversion.RasterToPoint(in_raster=seaweed_farm_present_tif, out_point_features=seaweed_farm_points_presence_shp, raster_field="Value")

    # Process: Buffer (Buffer) (analysis)
    seaweed_farm_buffer5km_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_buffer5km.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        arcpy.analysis.Buffer(in_features=seaweed_farm_points_presence_shp, out_feature_class=seaweed_farm_buffer5km_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

    # Process: Raster Calculator (Raster Calculator) (ia)
    chla_flow_acc_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\chla_flow_acc_norm.tif"
    Raster_Calculator = chla_flow_acc_norm_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        chla_flow_acc_norm_tif =  (("%chla_alow_acc.tif%"-"%chla_alow_acc.tif%".minimum)/ ("%chla_alow_acc.tif%".maximum - "%chla_alow_acc.tif%".minimum))*100
        chla_flow_acc_norm_tif.save(Raster_Calculator)


    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    seaweed_farm_present_buffer5km_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_present_buffer5km.tif"
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        arcpy.conversion.PolygonToRaster(in_features=seaweed_farm_buffer5km_shp_seaweed_farm_buffer5km, value_field="Id", out_rasterdataset=seaweed_farm_present_buffer5km_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="Id", cellsize="M:\\marin\\swoc\\work\\wiosym\\data\\reg\\grid\\grid\\v01\\grid_1km_v01.1.tif", build_rat="BUILD")

    # Process: Extract by Mask (Extract by Mask) (sa)
    seaweed_farm_present_eutrophication_relativ_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_present_eutrophication_relativ.tif"
    Extract_by_Mask = seaweed_farm_present_eutrophication_relativ_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        seaweed_farm_present_eutrophication_relativ_tif = arcpy.sa.ExtractByMask(in_raster=Chl_a_norm_int_tif, in_mask_data=seaweed_farm_present_buffer5km_tif)
        seaweed_farm_present_eutrophication_relativ_tif.save(Extract_by_Mask)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    seaweed_farm_1_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_1.tif"
    Raster_Calculator_2_ = seaweed_farm_1_tif
    seaweed_farm_1_tif =  seaweed_farm_present_eutrophication_relativ_tif+1
    seaweed_farm_1_tif.save(Raster_Calculator_2_)


    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    algeafarm_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[seaweed_farm_1_tif, grid_1km_v01_1_tif_2_], output_location=proc_3_, raster_dataset_name_with_extension="algeafarm_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    algeafarm_combine_grid_tif = arcpy.Raster(algeafarm_combine_grid_tif)

    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    algea_farming_v3_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\algea_farming_v3.tif"
    Raster_Calculator_3_ = algea_farming_v3_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        algea_farming_v3_tif =  ((algeafarm_combine_grid_tif- algeafarm_combine_grid_tif.minimum)/(algeafarm_combine_grid_tif.maximum-algeafarm_combine_grid_tif.minimum))*100
        algea_farming_v3_tif.save(Raster_Calculator_3_)


    # Process: Project (2) (Project) (management)
    seaweed_farm_project = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_project"
    arcpy.management.Project(in_dataset=seaweed_farm_Multipolygons, out_dataset=seaweed_farm_project, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

    # Process: Union (Union) (analysis)
    seaweed_farm_reg_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\algea_farming\\proc\\seaweed_farm_reg.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        arcpy.analysis.Union(in_features=[[seaweed_farm_moz, ""], [seaweed_farm_project, ""]], out_feature_class=seaweed_farm_reg_shp, join_attributes="ALL", cluster_tolerance="", gaps="GAPS")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\aquaculture_mariculture\v01\proc\aquaculture\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\aquaculture_mariculture\v01\proc\aquaculture\Default.gdb"):
        algea_farm_v3()
