---
title: "R Notebook"
---

```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(rio)
library(gsheet)
library(fs)
```

# Import all 
```{r}
ver <- "v2.2"
sourceloc <- "../data/"
metaloc <- "../data_raw/"
#meta <- list.files(path = "./data/", pattern = "_sourcesym.txt", recursive = T)
source.long <- list.files(path = sourceloc, pattern = "_sourcesym.txt", recursive = T, full.names = T)
source.short <- basename(source.long)

meta.long <- list.files(path = metaloc, pattern = "_metasym.txt", recursive = T, full.names = T)
meta.short <- basename(meta.long)

#layers <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1JIV92XisuBctBoVT53yqj0orPNRVyRQVEDtMq7R0fKw/edit?usp=sharing")
layers <- rio::import(paste0("layers_metadata/", ver, "/layers_metadata_", ver, ".xlsx"))
layers <- filter(layers, is.na(file_name) == FALSE)
```

```{r}
df <- data.frame("short_name" = as.character(1:nrow(layers)), "sourcesym" = NA)

for(i in 1:nrow(layers)){
  v1 <- layers$sourcesym[i]
  v2 <- source.short
  m <- source.long[which(v2 %in% v1)]
  
  df$short_name[i] <- layers$short_name[i]
  df$sourcesym[i] <- m
}
```

## Create list of all metasym (data_raw) filenames mentioned in sourcesysm (data) files
```{r}
l <- vector(mode = "list", length = nrow(df))
for(i in 1:nrow(df)){
  f <- paste0(sourceloc, df$sourcesym[i])
  f <- read.table(f, header = T)
  l[[i]] <- f$id
  #cat("\nIt", i, f$id)
}

```

## Copy only used data from full data_raw to data_raw_used
```{r}
metasym <- unlist(l)
source_dir <- "E:/data_raw" # Repeat for dirrent source directories (e.g. local, github)
destination_dir <- "E:/data_raw_used"

# Create the destination directory if it doesn't exist
if (!dir.exists(destination_dir)) {
  dir.create(destination_dir, recursive = TRUE)
}
all_dir <- dir_ls(source_dir, type = "directory", recurse = TRUE)
for(i in 1:length(metasym)){
  temp <- all_dir[grepl(metasym[i], basename(all_dir), ignore.case = FALSE)]
  if(i == 1){matching_dir <- temp} else {matching_dir <- c(matching_dir, temp)}
}
names(matching_dir) <- NULL
matching_dir <- unique(matching_dir)

# Copy files
for(i in 1:length(matching_dir)){
  file_source <- matching_dir[i]
  file_dest <- gsub(source_dir, destination_dir, file_source)
  
  if(!file.exists(file_dest)){
    dir.create(dirname(file_dest), recursive = TRUE)
    file.copy(file_source, dirname(file_dest), recursive = TRUE)
  }
  cat("\nCopied", file_source, "to", file_dest)
}
```


*************************************
```{r}
layers$cits <- NA

for(i in 1:length(l)){
  cits <- NULL
  
  for(j in 1:length(l[[i]])){
    p <- paste0(l[[i]][j], "_metasym.txt")
    f <- list.files(path = metaloc, pattern = p, recursive = T, full.names = T)
    f <- read.table(f[1], header = F)
    f <- setNames(data.frame(t(f[,-1])), f[,1])
    cits <- c(cits, f$citation)
  }
  
  cits <- paste(cits, collapse = "; ")
  layers$cits[i] <- cits
}
```

```{r}
layers$source_url <- NA

for(i in 1:length(l)){
  cits <- NULL
  
  for(j in 1:length(l[[i]])){
    p <- paste0(l[[i]][j], "_metasym.txt")
    f <- list.files(path = metaloc, pattern = p, recursive = T, full.names = T)
    f <- read.table(f[1], header = F)
    f <- setNames(data.frame(t(f[,-1])), f[,1])
    cits <- c(cits, f$source)
  }
  
  cits <- paste(cits, collapse = "; ")
  layers$source_url[i] <- cits
}
```



