# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-12 19:22:55
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *

def dumping_v2():  # dumping_v2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
        dumping_TSM_grid_reverse_tif_dumping_TSM_grid_reverse_tif = arcpy.Raster("ModelBuilder\\dumping_TSM_grid_reverse.tif:dumping_TSM_grid_reverse.tif")
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
        dumping_mask_tsm_tif_dumping_mask_tsm_tif = arcpy.Raster("ModelBuilder\\dumping_mask_tsm.tif:dumping_mask_tsm.tif")
        v02 = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02"
        WIOSym_dumpimg_shipping = "WIOSym_dumpimg_shipping"
        WIOSym_dumpimg_landbase = "WIOSym_dumpimg_landbase"
        TSM_int_tif = arcpy.Raster("TSM_int.tif")
        dumping_merg_project_5km_buffer_dissolve_shp_dumping_merg_project_5km_buffer_dissolve = "ModelBuilder\\dumping_merg_project_5km_buffer_dissolve.shp:dumping_merg_project_5km_buffer_dissolve"
        Dumping = "Dumping"

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        dumping_TSM_grid_reverse_setnull_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v01\\proc\\dumping_TSM_grid_reverse_setnull.tif"
        Raster_Calculator_2_ = dumping_TSM_grid_reverse_setnull_tif
        with arcpy.EnvManager(cellSize=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            dumping_TSM_grid_reverse_setnull_tif =  SetNull(dumping_TSM_grid_reverse_tif_dumping_TSM_grid_reverse_tif<0, dumping_TSM_grid_reverse_tif_dumping_TSM_grid_reverse_tif)
            dumping_TSM_grid_reverse_setnull_tif.save(Raster_Calculator_2_)


        # Process: Raster Calculator (Raster Calculator) (ia)
        grid_0_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v01\\proc\\grid_0.tif"
        Raster_Calculator = grid_0_tif
        with arcpy.EnvManager(cellSize=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            grid_0_tif =  grid_1km_v01_1_tif *0
            grid_0_tif.save(Raster_Calculator)


        # Process: Raster Calculator (4) (Raster Calculator) (ia)
        dumping_tsm_reverse_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\dumping_tsm_reverse.tif"
        Raster_Calculator_4_ = dumping_tsm_reverse_tif
        with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            dumping_tsm_reverse_tif = (dumping_mask_tsm_tif_dumping_mask_tsm_tif*(-1))
            dumping_tsm_reverse_tif.save(Raster_Calculator_4_)


        # Process: Raster Calculator (5) (Raster Calculator) (sa)
        dumpling_setnull_TSM_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\dumpling_setnull_TSM.tif"
        Raster_Calculator_5_ = dumpling_setnull_TSM_tif
        with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask=r"ModelBuilder\dumping_grid.tif:dumping_grid.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            dumpling_setnull_TSM_tif =  SetNull(dumping_tsm_reverse_tif< 0, dumping_tsm_reverse_tif)
            dumpling_setnull_TSM_tif.save(Raster_Calculator_5_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        dumping_v2_tif = arcpy.management.MosaicToNewRaster(input_rasters=[grid_0_tif, dumpling_setnull_TSM_tif], output_location=v02, raster_dataset_name_with_extension="dumping_v2.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
        dumping_v2_tif = arcpy.Raster(dumping_v2_tif)

        # Process: Project (Project) (management)
        dumping_west_coast_project_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\dumping_west_coast_project.shp"
        arcpy.management.Project(in_dataset=Dumping, out_dataset=dumping_west_coast_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (Buffer) (analysis)
        buffer_dumping_westcoast_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\buffer_dumping_westcoast.shp"
        arcpy.analysis.Buffer(in_features=dumping_west_coast_project_shp, out_feature_class=buffer_dumping_westcoast_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Union (Union) (analysis)
        dumping_merg_project_5km_buffer_combine_west = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc\\peirs_docks\\Default.gdb\\dumping_merg_project_5km_buffer_combine_west"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
            arcpy.analysis.Union(in_features=[[dumping_merg_project_5km_buffer_dissolve_shp_dumping_merg_project_5km_buffer_dissolve, ""], [buffer_dumping_westcoast_shp, ""]], out_feature_class=dumping_merg_project_5km_buffer_combine_west, join_attributes="ALL", cluster_tolerance="", gaps="GAPS")

        # Process: Polygon to Raster (Polygon to Raster) (conversion)
        combine_buffer_east_west_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\combine_buffer_east_west.tif"
        with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            arcpy.conversion.PolygonToRaster(in_features=dumping_merg_project_5km_buffer_combine_west, value_field="value", out_rasterdataset=combine_buffer_east_west_tif, cell_assignment="CELL_CENTER", priority_field="value", cellsize=grid_1km_v01_1_tif, build_rat="BUILD")

        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        dumping_5km_mask_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\dumping_5km_mask.tif"
        Raster_Calculator_3_ = dumping_5km_mask_tif
        with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            dumping_5km_mask_tif =  (combine_buffer_east_west_tif *0)+1
            dumping_5km_mask_tif.save(Raster_Calculator_3_)


        # Process: Extract by Mask (Extract by Mask) (sa)
        dumping_mask_tsm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\dumping\\v02\\proc\\dumping_mask_tsm.tif"
        Extract_by_Mask = dumping_mask_tsm_tif
        with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            dumping_mask_tsm_tif = arcpy.sa.ExtractByMask(in_raster=TSM_int_tif, in_mask_data=dumping_5km_mask_tif)
            dumping_mask_tsm_tif.save(Extract_by_Mask)


if __name__ == '__main__':
    dumping_v2()
