# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-13 09:27:34
"""
import arcpy
from arcpy.ia import *

def land_rec_v2():  # land_rec_v2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
        WIOSym_Land_reclaimation = "WIOSym_Land_reclaimation"
        land_rec_5km_shp_land_rec_5km = "ModelBuilder\\land_rec_5km.shp:land_rec_5km"
        Land_reclaimation = "Land_reclaimation"
        proc = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc"
        proc_2_ = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc"
        land_reclaimation_x10_tif_2_ = arcpy.Raster("M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_reclaimation_x10.tif")
        grid_0proxy_tif = arcpy.Raster("M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\piers_docks\\v01\\proc\\peirs_docks\\grid_0proxy.tif")
        proc_3_ = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc"
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")

        # Process: Project (2) (Project) (management)
        land_rec_project_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_project.shp"
        arcpy.management.Project(in_dataset=WIOSym_Land_reclaimation, out_dataset=land_rec_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_EASE-Grid_2.0_Global\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",30.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (Buffer) (analysis)
        land_rec_5km_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v01\\proc\\land_rec_5km.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
            arcpy.analysis.Buffer(in_features=land_rec_project_shp, out_feature_class=land_rec_5km_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Project (Project) (management)
        land_rec_west_project = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_rec_west_project"
        arcpy.management.Project(in_dataset=Land_reclaimation, out_dataset=land_rec_west_project, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

        # Process: Buffer (2) (Buffer) (analysis)
        land_rec_buffer_5km_west_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_rec_buffer_5km_west.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
            arcpy.analysis.Buffer(in_features=land_rec_west_project, out_feature_class=land_rec_buffer_5km_west_shp, buffer_distance_or_field="5 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Merge (Merge) (management)
        land_rec_merg_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_rec_merg.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
            arcpy.management.Merge(inputs=[land_rec_5km_shp_land_rec_5km, land_rec_buffer_5km_west_shp], output=land_rec_merg_shp, field_mappings="Id \"Id\" true true false 6 Long 0 6,First,#,ModelBuilder\\land_rec_5km.shp:land_rec_5km,Id,-1,-1,M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_rec_buffer_5km_west.shp,Id,-1,-1;value \"value\" true true false 10 Long 0 10,First,#,ModelBuilder\\land_rec_5km.shp:land_rec_5km,value,-1,-1", add_source="NO_SOURCE_INFO")

        # Process: Polygon to Raster (Polygon to Raster) (conversion)
        land_reclaimation_Ratser_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_reclaimation_Ratser.tif"
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            arcpy.conversion.PolygonToRaster(in_features=land_rec_merg_shp, value_field="value", out_rasterdataset=land_reclaimation_Ratser_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="NONE", cellsize="grid_1km_v01.1.tif", build_rat="BUILD")

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        land_reclaimation_x10_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_reclaimation_x10.tif"
        Raster_Calculator_2_ = land_reclaimation_x10_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            land_reclaimation_x10_tif = land_reclaimation_Ratser_tif +10
            land_reclaimation_x10_tif.save(Raster_Calculator_2_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            land_rec_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[land_reclaimation_x10_tif_2_, grid_0proxy_tif], output_location=proc_3_, raster_dataset_name_with_extension="land_rec_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            land_rec_combine_grid_tif = arcpy.Raster(land_rec_combine_grid_tif)

        # Process: Extract by Mask (3) (Extract by Mask) (sa)
        land_rec_10_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\proc\\land_rec_10.tif"
        Extract_by_Mask_3_ = land_rec_10_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\piers_docks\v01\proc\peirs_docks\Default.gdb"):
            land_rec_10_tif = arcpy.sa.ExtractByMask(in_raster=land_rec_combine_grid_tif, in_mask_data=grid_1km_v01_1_tif)
            land_rec_10_tif.save(Extract_by_Mask_3_)


        # Process: Reclassify (Reclassify) (sa)
        land_reclaimation_v2_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\land_reclaimation\\v02\\land_reclaimation_v2.tif"
        Reclassify = land_reclaimation_v2_tif
        with arcpy.EnvManager(cellSize=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            land_reclaimation_v2_tif = arcpy.sa.Reclassify(in_raster=land_rec_10_tif, reclass_field="Value", remap="0 0;10 1", missing_values="DATA")
            land_reclaimation_v2_tif.save(Reclassify)


if __name__ == '__main__':
    land_rec_v2()
