# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-17 19:12:52
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def Nutrient_input():  # Nutrient_input

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
        wiosym_data_bounding_box_v01 = "wiosym_data_bounding_box_v01"
        woa18_all_n00mn01 = "woa18_all_n00mn01"
        nitrate_noaa_wio_shp_nitrate_noaa_wio = "ModelBuilder\\nitrate_noaa_wio.shp:nitrate_noaa_wio"
        grid_1km_0_v01_1_tif = arcpy.Raster("grid_1km_0_v01.1.tif")
        proc_ = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_"
        woa18_all_p00mn01 = "woa18_all_p00mn01"
        phosphate_noaa_wio_shp_phosphate_noaa_wio = "ModelBuilder\\phosphate_noaa_wio.shp:phosphate_noaa_wio"
        phosphate_noaa_2018_ratser_project_tif_2_ = arcpy.Raster("phosphate_noaa_2018._ratser_project.tif")
        grid_1km_0_v01_1_tif_2_ = arcpy.Raster("M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\grid\\grid\\v01\\grid_1km_0_v01.1.tif")
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
        v1_total_mean_velocity_norm_int_tif = arcpy.Raster("v1_total_mean_velocity_norm_int.tif")
        Chl_a_b1_tif = arcpy.Raster("Chl_a_b1.tif")
        total_mean_nitrogen1_tif = arcpy.Raster("total_mean_nitrogen1.tif")
        mean_postassium2_tif = arcpy.Raster("mean_postassium2.tif")
        mean_phosphorus2_tif = arcpy.Raster("mean_phosphorus2.tif")
        grid_1km_v01_1_tif_2_ = arcpy.Raster("grid_1km_v01.1.tif")
        v1_flow_acc_pres_norm_int_tif = arcpy.Raster("v1_flow_acc_pres_norm_int.tif")
        v1_volumn_runoff_norm_int_tif = arcpy.Raster("v1_volumn_runoff_norm_int.tif")

        # Process: Intersect (2) (Intersect) (analysis)
        nitrate_noaa_wio_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\nitrate_noaa_wio.shp"
        arcpy.analysis.Intersect(in_features=[[wiosym_data_bounding_box_v01, ""], [woa18_all_n00mn01, ""]], out_feature_class=nitrate_noaa_wio_shp, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

        # Process: Point to Raster (2) (Point to Raster) (conversion)
        nitrate_noaa_2018_ratser_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\nitrate_noaa_2018_ratser.tif"
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
            arcpy.conversion.PointToRaster(in_features=nitrate_noaa_wio_shp_nitrate_noaa_wio, value_field="SURFACE", out_rasterdataset=nitrate_noaa_2018_ratser_tif, cell_assignment="MOST_FREQUENT", priority_field="FID_wiosym", cellsize="1", build_rat="BUILD")

        # Process: Project Raster (2) (Project Raster) (management)
        nitrate_noaa_2018_ratser_project_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\nitrate_noaa_2018._ratser_project.tif"
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", nodata="MAP_DOWN", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS", snapRaster="grid_1km_0_v01.1.tif"):
            arcpy.management.ProjectRaster(in_raster=nitrate_noaa_2018_ratser_tif, out_raster=nitrate_noaa_2018_ratser_project_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS84\",SPHEROID[\"WGS84\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
            nitrate_noaa_2018_ratser_project_tif = arcpy.Raster(nitrate_noaa_2018_ratser_project_tif)

        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        nitrate_noaa_2018_ratser_project_setnull_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\nitrate_noaa_2018._ratser_project_setnull.tif"
        Raster_Calculator_3_ = nitrate_noaa_2018_ratser_project_setnull_tif
        nitrate_noaa_2018_ratser_project_setnull_tif =  SetNull(nitrate_noaa_2018_ratser_project_tif<0, nitrate_noaa_2018_ratser_project_tif) 
        nitrate_noaa_2018_ratser_project_setnull_tif.save(Raster_Calculator_3_)


        # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
            Mosaic_grid_noaa_nitrate_tif = arcpy.management.MosaicToNewRaster(input_rasters=[nitrate_noaa_2018_ratser_project_setnull_tif, grid_1km_0_v01_1_tif], output_location=proc_, raster_dataset_name_with_extension="Mosaic_grid_noaa_nitrate.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            Mosaic_grid_noaa_nitrate_tif = arcpy.Raster(Mosaic_grid_noaa_nitrate_tif)

        # Process: Focal Statistics (2) (Focal Statistics) (ia)
        Nitrate_focal_noaa_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\Nitrate_focal_noaa.tif"
        Focal_Statistics_2_ = Nitrate_focal_noaa_tif
        Nitrate_focal_noaa_tif = arcpy.ia.FocalStatistics(in_raster=Mosaic_grid_noaa_nitrate_tif, neighborhood="Wedge 100 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
        Nitrate_focal_noaa_tif.save(Focal_Statistics_2_)


        # Process: Intersect (3) (Intersect) (analysis)
        phosphate_noaa_wio_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_noaa_wio.shp"
        arcpy.analysis.Intersect(in_features=[[wiosym_data_bounding_box_v01, ""], [woa18_all_p00mn01, ""]], out_feature_class=phosphate_noaa_wio_shp, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

        # Process: Point to Raster (4) (Point to Raster) (conversion)
        phosephate_noaa_2018_ratser_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosephate_noaa_2018_ratser.tif"
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
            arcpy.conversion.PointToRaster(in_features=phosphate_noaa_wio_shp_phosphate_noaa_wio, value_field="SURFACE", out_rasterdataset=phosephate_noaa_2018_ratser_tif, cell_assignment="MOST_FREQUENT", priority_field="FID_wiosym", cellsize="1", build_rat="BUILD")

        # Process: Project Raster (3) (Project Raster) (management)
        phosphate_noaa_2018_ratser_project_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_noaa_2018._ratser_project.tif"
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", nodata="MAP_DOWN", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS", snapRaster="grid_1km_0_v01.1.tif"):
            arcpy.management.ProjectRaster(in_raster=phosephate_noaa_2018_ratser_tif, out_raster=phosphate_noaa_2018_ratser_project_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS84\",SPHEROID[\"WGS84\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
            phosphate_noaa_2018_ratser_project_tif = arcpy.Raster(phosphate_noaa_2018_ratser_project_tif)

        # Process: Raster Calculator (5) (Raster Calculator) (ia)
        phosphate_noaa_2018_ratser_project_setnull_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_noaa_2018._ratser_project_setnull.tif"
        Raster_Calculator_5_ = phosphate_noaa_2018_ratser_project_setnull_tif
        phosphate_noaa_2018_ratser_project_setnull_tif =  SetNull(phosphate_noaa_2018_ratser_project_tif<0, phosphate_noaa_2018_ratser_project_tif_2_) 
        phosphate_noaa_2018_ratser_project_setnull_tif.save(Raster_Calculator_5_)


        # Process: Mosaic To New Raster (4) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
            Mosaic_grid_noaa_phosphate_tif = arcpy.management.MosaicToNewRaster(input_rasters=[phosphate_noaa_2018_ratser_project_setnull_tif, grid_1km_0_v01_1_tif_2_], output_location=proc_, raster_dataset_name_with_extension="Mosaic_grid_noaa_phosphate.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            Mosaic_grid_noaa_phosphate_tif = arcpy.Raster(Mosaic_grid_noaa_phosphate_tif)

        # Process: Focal Statistics (3) (Focal Statistics) (ia)
        phosphate_focal_noaa_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_focal_noaa.tif"
        Focal_Statistics_3_ = phosphate_focal_noaa_tif
        phosphate_focal_noaa_tif = arcpy.ia.FocalStatistics(in_raster=Mosaic_grid_noaa_phosphate_tif, neighborhood="Wedge 100 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
        phosphate_focal_noaa_tif.save(Focal_Statistics_3_)


        # Process: Extract by Mask (6) (Extract by Mask) (sa)
        phosphate_noaa_2018_ratser_focal_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_noaa_2018_ratser_focal_grid.tif"
        Extract_by_Mask_6_ = phosphate_noaa_2018_ratser_focal_grid_tif
        with arcpy.EnvManager(mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            phosphate_noaa_2018_ratser_focal_grid_tif = arcpy.sa.ExtractByMask(in_raster=phosphate_focal_noaa_tif, in_mask_data=grid_1km_v01_1_tif)
            phosphate_noaa_2018_ratser_focal_grid_tif.save(Extract_by_Mask_6_)


        # Process: Project Raster (Project Raster) (management)
        chl_a_project_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\chl_a_project.tif"
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", nodata="MAXIMUM", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_0_v01.1.tif"):
            arcpy.management.ProjectRaster(in_raster=Chl_a_b1_tif, out_raster=chl_a_project_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
            chl_a_project_tif = arcpy.Raster(chl_a_project_tif)

        # Process: Extract by Mask (4) (Extract by Mask) (sa)
        chl_a_extractgrid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\chl_a_extractgrid.tif"
        Extract_by_Mask_4_ = chl_a_extractgrid_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", mask="grid_1km_0_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_0_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            chl_a_extractgrid_tif = arcpy.sa.ExtractByMask(in_raster=chl_a_project_tif, in_mask_data=grid_1km_0_v01_1_tif)
            chl_a_extractgrid_tif.save(Extract_by_Mask_4_)


        # Process: Focal Statistics (Focal Statistics) (ia)
        chl_a_extractgrid_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\chl_a_extractgrid_focal.tif"
        Focal_Statistics = chl_a_extractgrid_focal_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            chl_a_extractgrid_focal_tif = arcpy.ia.FocalStatistics(in_raster=chl_a_extractgrid_tif, neighborhood="Wedge 7 0 360 CELL", statistics_type="PERCENTILE", ignore_nodata="DATA", percentile_value=60)
            chl_a_extractgrid_focal_tif.save(Focal_Statistics)


        # Process: Extract by Mask (5) (Extract by Mask) (sa)
        chl_a_extractgrid_focal_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\chl_a_extractgrid_focal_grid.tif"
        Extract_by_Mask_5_ = chl_a_extractgrid_focal_grid_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", mask="grid_1km_0_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_0_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            chl_a_extractgrid_focal_grid_tif = arcpy.sa.ExtractByMask(in_raster=chl_a_extractgrid_focal_tif, in_mask_data=grid_1km_0_v01_1_tif)
            chl_a_extractgrid_focal_grid_tif.save(Extract_by_Mask_5_)


        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        chl_a_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\chl_a_norm.tif"
        Raster_Calculator_2_ = chl_a_norm_tif
        chl_a_norm_tif = ((chl_a_extractgrid_focal_grid_tif- chl_a_extractgrid_focal_grid_tif.minimum) / (chl_a_extractgrid_focal_grid_tif.maximum- chl_a_extractgrid_focal_grid_tif.minimum))*100
        chl_a_norm_tif.save(Raster_Calculator_2_)


        # Process: Raster Calculator (6) (Raster Calculator) (ia)
        Chl_a_norm_int_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\Chl_a_norm_int.tif"
        Raster_Calculator_6_ = Chl_a_norm_int_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            Chl_a_norm_int_tif =  Int(chl_a_norm_tif)
            Chl_a_norm_int_tif.save(Raster_Calculator_6_)


        # Process: Extract by Mask (Extract by Mask) (sa)
        mean_nitrogen_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\mean_nitrogen.tif"
        Extract_by_Mask = mean_nitrogen_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", mask="grid_1km_0_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_0_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            mean_nitrogen_tif = arcpy.sa.ExtractByMask(in_raster=total_mean_nitrogen1_tif, in_mask_data=grid_1km_0_v01_1_tif)
            mean_nitrogen_tif.save(Extract_by_Mask)


        # Process: Extract by Mask (2) (Extract by Mask) (sa)
        mean_potassium_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\mean_potassium.tif"
        Extract_by_Mask_2_ = mean_potassium_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", mask="grid_1km_0_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_0_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            mean_potassium_tif = arcpy.sa.ExtractByMask(in_raster=mean_postassium2_tif, in_mask_data=grid_1km_0_v01_1_tif)
            mean_potassium_tif.save(Extract_by_Mask_2_)


        # Process: Extract by Mask (3) (Extract by Mask) (sa)
        mean_phosphorus_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\mean_phosphorus.tif"
        Extract_by_Mask_3_ = mean_phosphorus_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_0_v01.1.tif", mask="grid_1km_0_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_0_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            mean_phosphorus_tif = arcpy.sa.ExtractByMask(in_raster=mean_phosphorus2_tif, in_mask_data=grid_1km_0_v01_1_tif)
            mean_phosphorus_tif.save(Extract_by_Mask_3_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            mosiac_nutrient_tif = arcpy.management.MosaicToNewRaster(input_rasters=[mean_nitrogen_tif, mean_potassium_tif, mean_phosphorus_tif], output_location=proc_, raster_dataset_name_with_extension="mosiac_nutrient.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="REJECT")[0]
            mosiac_nutrient_tif = arcpy.Raster(mosiac_nutrient_tif)

        # Process: Raster Calculator (Raster Calculator) (ia)
        mosiac_nutrient_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\mosiac_nutrient_norm.tif"
        Raster_Calculator = mosiac_nutrient_norm_tif
        mosiac_nutrient_norm_tif =  ((mosiac_nutrient_tif- mosiac_nutrient_tif.minimum) / (mosiac_nutrient_tif.maximum- mosiac_nutrient_tif.minimum))*100
        mosiac_nutrient_norm_tif.save(Raster_Calculator)


        # Process: Focal Statistics (4) (Focal Statistics) (ia)
        ISA_nutrient_land_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\ISA_nutrient_land_focal.tif"
        Focal_Statistics_4_ = ISA_nutrient_land_focal_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            ISA_nutrient_land_focal_tif = arcpy.ia.FocalStatistics(in_raster=mosiac_nutrient_norm_tif, neighborhood="Wedge 10 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=60)
            ISA_nutrient_land_focal_tif.save(Focal_Statistics_4_)


        # Process: Extract by Mask (8) (Extract by Mask) (sa)
        ISA_nutrient_NPK_focal_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\ISA_nutrient_NPK_focal_grid.tif"
        Extract_by_Mask_8_ = ISA_nutrient_NPK_focal_grid_tif
        with arcpy.EnvManager(mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", 
                              snapRaster="grid_1km_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            ISA_nutrient_NPK_focal_grid_tif = arcpy.sa.ExtractByMask(in_raster=ISA_nutrient_land_focal_tif, in_mask_data=grid_1km_v01_1_tif)
            ISA_nutrient_NPK_focal_grid_tif.save(Extract_by_Mask_8_)


        # Process: Raster Calculator (8) (Raster Calculator) (ia)
        ISA_nutrient_NPK_focal_grid_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\ISA_nutrient_NPK_focal_grid_norm.tif"
        Raster_Calculator_8_ = ISA_nutrient_NPK_focal_grid_norm_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="GEOGCS["GCS_WGS_1984",DATUM["D_WGS84",SPHEROID["WGS84",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]", 
                              scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", snapRaster="grid_1km_v01.1.tif", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            ISA_nutrient_NPK_focal_grid_norm_tif =  ((ISA_nutrient_NPK_focal_grid_tif-ISA_nutrient_NPK_focal_grid_tif.minimum)/(ISA_nutrient_NPK_focal_grid_tif.maximum- ISA_nutrient_NPK_focal_grid_tif.minimum))*100
            ISA_nutrient_NPK_focal_grid_norm_tif.save(Raster_Calculator_8_)


        # Process: Raster Calculator (9) (Raster Calculator) (ia)
        ISA_nutrient_NPK_focal_grid_norm_int_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\ISA_nutrient_NPK_focal_grid_norm_int.tif"
        Raster_Calculator_9_ = ISA_nutrient_NPK_focal_grid_norm_int_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            ISA_nutrient_NPK_focal_grid_norm_int_tif =  Int(ISA_nutrient_NPK_focal_grid_norm_tif)
            ISA_nutrient_NPK_focal_grid_norm_int_tif.save(Raster_Calculator_9_)


        # Process: Mosaic To New Raster (3) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
            phosphate_nitrate_noaa_combine_mosiac_tif = arcpy.management.MosaicToNewRaster(input_rasters=[Mosaic_grid_noaa_nitrate_tif, Mosaic_grid_noaa_phosphate_tif], output_location=proc_, raster_dataset_name_with_extension="phosphate_nitrate_noaa_combine_mosiac.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="REJECT")[0]
            phosphate_nitrate_noaa_combine_mosiac_tif = arcpy.Raster(phosphate_nitrate_noaa_combine_mosiac_tif)

        # Process: Clip Raster (Clip Raster) (management)
        phosphate_nitrate_noaa_combine_mosiac_grid_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_nitrate_noaa_combine_mosiac_grid.tif"
        arcpy.management.Clip(in_raster=phosphate_nitrate_noaa_combine_mosiac_tif, rectangle="-441000 -4171000 7192000 1790000", out_raster=phosphate_nitrate_noaa_combine_mosiac_grid_tif, in_template_dataset=grid_1km_v01_1_tif_2_, nodata_value="-3,402823e+38", clipping_geometry="NONE", maintain_clipping_extent="NO_MAINTAIN_EXTENT")
        phosphate_nitrate_noaa_combine_mosiac_grid_tif = arcpy.Raster(phosphate_nitrate_noaa_combine_mosiac_grid_tif)

        # Process: Focal Statistics (5) (Focal Statistics) (ia)
        phosphate_nitrate_noaa_combine_mosiac_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\phosphate_nitrate_noaa_combine_mosiac_focal.tif"
        Focal_Statistics_5_ = phosphate_nitrate_noaa_combine_mosiac_focal_tif
        phosphate_nitrate_noaa_combine_mosiac_focal_tif = arcpy.ia.FocalStatistics(in_raster=phosphate_nitrate_noaa_combine_mosiac_grid_tif, neighborhood="Wedge 100 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
        phosphate_nitrate_noaa_combine_mosiac_focal_tif.save(Focal_Statistics_5_)


        # Process: Extract by Mask (7) (Extract by Mask) (sa)
        _1_NP_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\1_NP_focal.tif"
        Extract_by_Mask_7_ = _1_NP_focal_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            _1_NP_focal_tif = arcpy.sa.ExtractByMask(in_raster=phosphate_nitrate_noaa_combine_mosiac_focal_tif, in_mask_data=grid_1km_v01_1_tif)
            _1_NP_focal_tif.save(Extract_by_Mask_7_)


        # Process: Raster Calculator (4) (Raster Calculator) (ia)
        _1_nitrate_phosphate_noaa_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\1_nitrate_phosphate_noaa_norm_.tif"
        Raster_Calculator_4_ = _1_nitrate_phosphate_noaa_norm_tif
        _1_nitrate_phosphate_noaa_norm_tif = ((_1_NP_focal_tif - _1_NP_focal_tif.minimum)/( _1_NP_focal_tif.maximum- _1_NP_focal_tif.minimum))*100
        _1_nitrate_phosphate_noaa_norm_tif.save(Raster_Calculator_4_)


        # Process: Raster Calculator (7) (Raster Calculator) (ia)
        NP_noaa_2018_norm_int_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\NP_noaa_2018_norm_int.tif"
        Raster_Calculator_7_ = NP_noaa_2018_norm_int_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\pres\Nutrient_input\v01\proc\nutrient_input_proj\Default.gdb"):
            NP_noaa_2018_norm_int_tif =  Int( _1_nitrate_phosphate_noaa_norm_tif)
            NP_noaa_2018_norm_int_tif.save(Raster_Calculator_7_)


        # Process: Weighted Sum (Weighted Sum) (ia)
        nutrient_input_weight_prediction_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\proc_\\nutrient_input_weight_prediction.tif"
        Weighted_Sum = nutrient_input_weight_prediction_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", cellSizeProjectionMethod="PRESERVE_RESOLUTION", mask="grid_1km_v01.1.tif", 
                              outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            nutrient_input_weight_prediction_tif = arcpy.ia.WeightedSum(in_rasters=[[v1_total_mean_velocity_norm_int_tif, "Value", 3], [Chl_a_norm_int_tif, "Value", 15], [ISA_nutrient_NPK_focal_grid_norm_int_tif, "Value", 15], [NP_noaa_2018_norm_int_tif, "Value", 15], [v1_flow_acc_pres_norm_int_tif, "Value", 15], [v1_volumn_runoff_norm_int_tif, "Value", 3]])
            nutrient_input_weight_prediction_tif.save(Weighted_Sum)


        # Process: Raster Calculator (10) (Raster Calculator) (ia)
        Nutrient_input_v01_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\Nutrient_input\\v01\\Nutrient_input_v01.tif"
        Raster_Calculator_10_ = Nutrient_input_v01_tif
        with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            Nutrient_input_v01_tif = ((nutrient_input_weight_prediction_tif- nutrient_input_weight_prediction_tif.minimum)/( nutrient_input_weight_prediction_tif.maximum- nutrient_input_weight_prediction_tif.minimum))*100
            Nutrient_input_v01_tif.save(Raster_Calculator_10_)


if __name__ == '__main__':
    Nutrient_input()
