# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-08 00:49:46
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *

def nutrient_inputv2_aug2022():  # nutrient_inputv2_aug2022

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp39944\164b38c0-b0f4-48b9-83d7-1fae5c8082bc\Default.gdb", workspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp39944\164b38c0-b0f4-48b9-83d7-1fae5c8082bc\Default.gdb"):
        Chl_a_2017_2021_ave_tif = arcpy.Raster("Chl_a_2017-2021_ave.tif")
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")

        # Process: Project Raster (Project Raster) (management)
        Chla_project_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v01\\proc\\nutrient_input_proj\\Chla_project.tif"
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp39944\164b38c0-b0f4-48b9-83d7-1fae5c8082bc\Default.gdb", 
                              snapRaster="grid_1km_v01.1.tif", workspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp39944\164b38c0-b0f4-48b9-83d7-1fae5c8082bc\Default.gdb"):
            arcpy.management.ProjectRaster(in_raster=Chl_a_2017_2021_ave_tif, out_raster=Chla_project_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size=grid_1km_v01_1_tif, geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
            Chla_project_tif = arcpy.Raster(Chla_project_tif)

        # Process: Raster Calculator (Raster Calculator) (ia)
        Chla_true_value_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v01\\proc\\nutrient_input_proj\\Chla_true_value.tif"
        Raster_Calculator = Chla_true_value_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            Chla_true_value_tif = Exp10(Chla_project_tif) 
            Chla_true_value_tif.save(Raster_Calculator)


        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        Nutrient_input_v02_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v01\\Nutrient_input_v02.tif"
        Raster_Calculator_2_ = Nutrient_input_v02_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            Nutrient_input_v02_tif =  SetNull (Chla_true_value_tif<3, Chla_true_value_tif)
            Nutrient_input_v02_tif.save(Raster_Calculator_2_)


if __name__ == '__main__':
    nutrient_inputv2_aug2022()
