# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-05-20 12:53:07
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *

def Mesophotic_coral_model():  # Mesophotic_coral_model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    gebco_2021_n18_0_s_42_0_w6_0_e80_0_tif = arcpy.Raster("gebco_2021_n18.0_s-42.0_w6.0_e80.0.tif")
    gebco_2021_n18_ProjectRaster_gebco_2021_n18_ProjectRaster_2_ = arcpy.Raster("ModelBuilder\\gebco_2021_n18_ProjectRaster:gebco_2021_n18_ProjectRaster")
    WCMC008_CoralReef2018_Py_v4_1 = "WCMC008_CoralReef2018_Py_v4_1"
    wiosym_grid_bounding_box_v01 = "wiosym_grid_bounding_box_v01"
    coral_reef_proportion_1km_v01_1_tif = arcpy.Raster("coral_reef_proportion_1km_v01.1.tif")
    proc = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc"
    gebco_2021_n18_ProjectRaster_gebco_2021_n18_ProjectRaster = arcpy.Raster("ModelBuilder\\gebco_2021_n18_ProjectRaster:gebco_2021_n18_ProjectRaster")

    # Process: Project Raster (Project Raster) (management)
    gebco_2021_n18_ProjectRaster = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\proc\\Default.gdb\\gebco_2021_n18_ProjectRaster"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        arcpy.management.ProjectRaster(in_raster=gebco_2021_n18_0_s_42_0_w6_0_e80_0_tif, out_raster=gebco_2021_n18_ProjectRaster, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="447,11160205598 447,11160205598", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
        gebco_2021_n18_ProjectRaster = arcpy.Raster(gebco_2021_n18_ProjectRaster)

    # Process: Clip (Clip) (analysis)
    wcmc_coral_wio_shp = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\wcmc_coral_wio.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        arcpy.analysis.Clip(in_features=WCMC008_CoralReef2018_Py_v4_1, clip_features=wiosym_grid_bounding_box_v01, out_feature_class=wcmc_coral_wio_shp, cluster_tolerance="")

    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    WCMC_coral_raster_area_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\WCMC_coral_raster_area.tif"
    arcpy.conversion.PolygonToRaster(in_features=wcmc_coral_wio_shp, value_field="METADATA_I", out_rasterdataset=WCMC_coral_raster_area_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="NONE", cellsize="250", build_rat="BUILD")

    # Process: Reclassify (2) (Reclassify) (sa)
    WCMC_coral_raster_area_250mWIO_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\WCMC_coral_raster_area_250mWIO.tif"
    Reclassify_2_ = WCMC_coral_raster_area_250mWIO_tif
    WCMC_coral_raster_area_250mWIO_tif = arcpy.sa.Reclassify(in_raster=WCMC_coral_raster_area_tif, reclass_field="Value", remap="1 82 1", missing_values="DATA")
    WCMC_coral_raster_area_250mWIO_tif.save(Reclassify_2_)


    # Process: Reclassify (3) (Reclassify) (sa)
    cora_reef_proportion_reclassify_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\cora_reef_proportion_reclassify.tif"
    Reclassify_3_ = cora_reef_proportion_reclassify_tif
    cora_reef_proportion_reclassify_tif = arcpy.sa.Reclassify(in_raster=coral_reef_proportion_1km_v01_1_tif, reclass_field="VALUE", remap="0 NODATA;1 1", missing_values="DATA")
    cora_reef_proportion_reclassify_tif.save(Reclassify_3_)


    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    coral_reef_combine_mosaic_wio_tif = arcpy.management.MosaicToNewRaster(input_rasters=[WCMC_coral_raster_area_250mWIO_tif, cora_reef_proportion_reclassify_tif], output_location=proc, raster_dataset_name_with_extension="coral_reef_combine_mosaic_wio.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=250, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
    coral_reef_combine_mosaic_wio_tif = arcpy.Raster(coral_reef_combine_mosaic_wio_tif)

    # Process: Reclassify (4) (Reclassify) (sa)
    cora_reef_proportion_combine_mosreclassify_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\cora_reef_proportion_combine_mosreclassify.tif"
    Reclassify_4_ = cora_reef_proportion_combine_mosreclassify_tif
    cora_reef_proportion_combine_mosreclassify_tif = arcpy.sa.Reclassify(in_raster=coral_reef_combine_mosaic_wio_tif, reclass_field="VALUE", remap="0 1;1 1", missing_values="DATA")
    cora_reef_proportion_combine_mosreclassify_tif.save(Reclassify_4_)


    # Process: Raster Calculator (Raster Calculator) (ia)
    ocean_depth_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\ocean_depth.tif"
    Raster_Calculator = ocean_depth_tif
    ocean_depth_tif =  SetNull(gebco_2021_n18_ProjectRaster_gebco_2021_n18_ProjectRaster>0, gebco_2021_n18_ProjectRaster_gebco_2021_n18_ProjectRaster)
    ocean_depth_tif.save(Raster_Calculator)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    depth_reverse_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\depth_reverse.tif"
    Raster_Calculator_2_ = depth_reverse_tif
    depth_reverse_tif =  ocean_depth_tif *(-1)
    depth_reverse_tif.save(Raster_Calculator_2_)


    # Process: Reclassify (Reclassify) (sa)
    mesophotic_zone30_150m_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\mesophotic_zone30-150m.tif"
    Reclassify = mesophotic_zone30_150m_tif
    mesophotic_zone30_150m_tif = arcpy.sa.Reclassify(in_raster=depth_reverse_tif, reclass_field="Value", remap="0 30 NODATA;30 150 1;150 7475 NODATA", missing_values="NODATA")
    mesophotic_zone30_150m_tif.save(Reclassify)


    # Process: Extract by Mask (Extract by Mask) (sa)
    mesophotic_coral_raster_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\proc\\mesophotic_coral_raster_.tif"
    Extract_by_Mask = mesophotic_coral_raster_tif
    mesophotic_coral_raster_tif = arcpy.sa.ExtractByMask(in_raster=cora_reef_proportion_combine_mosreclassify_tif, in_mask_data=mesophotic_zone30_150m_tif)
    mesophotic_coral_raster_tif.save(Extract_by_Mask)


    # Process: Resample (Resample) (management)
    mesophotic_coral_v0_1_0_1_km_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\bh_coral_mesophotic\\v01\\mesophotic_coral_v0.1.0_1_km.tif"
    arcpy.management.Resample(in_raster=mesophotic_coral_raster_tif, out_raster=mesophotic_coral_v0_1_0_1_km_tif, cell_size="1000 1000", resampling_type="NEAREST")
    mesophotic_coral_v0_1_0_1_km_tif = arcpy.Raster(mesophotic_coral_v0_1_0_1_km_tif)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\eco\bh_coral_mesophotic\v01\proc\proc\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\eco\bh_coral_mesophotic\v01\proc\proc\Default.gdb"):
        Mesophotic_coral_model()
