# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-12-13 14:36:26
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def air_pol_v1():  # air_pol_v1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\air_pol\v01\proc\air_pol\air_pol.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\air_pol\v01\proc\air_pol\air_pol.gdb"):
        SO2_wio21_tif = arcpy.Raster("SO2_wio21.tif")
        NO2_wio_tif = arcpy.Raster("NO2_wio.tif")
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        SO2_SetNull_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\SO2_SetNull.tif"
        Raster_Calculator_2_ = SO2_SetNull_tif
        SO2_SetNull_tif = SetNull(SO2_wio21_tif<0, SO2_wio21_tif)
        SO2_SetNull_tif.save(Raster_Calculator_2_)


        # Process: Project Raster (2) (Project Raster) (management)
        SO2_SetNull_ProjectRaster = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\air_pol\\air_pol.gdb\\SO2_SetNull_ProjectRaster"
        arcpy.management.ProjectRaster(in_raster=SO2_SetNull_tif, out_raster=SO2_SetNull_ProjectRaster, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", vertical="NO_VERTICAL")
        SO2_SetNull_ProjectRaster = arcpy.Raster(SO2_SetNull_ProjectRaster)

        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        NO2_setNull_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\NO2_setNull.tif"
        Raster_Calculator_3_ = NO2_setNull_tif
        NO2_setNull_tif = SetNull(NO2_wio_tif<0,NO2_wio_tif)
        NO2_setNull_tif.save(Raster_Calculator_3_)


        # Process: Project Raster (3) (Project Raster) (management)
        NO2_setNull_ProjectRaster = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\air_pol\\air_pol.gdb\\NO2_setNull_ProjectRaster"
        arcpy.management.ProjectRaster(in_raster=NO2_setNull_tif, out_raster=NO2_setNull_ProjectRaster, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="", vertical="NO_VERTICAL")
        NO2_setNull_ProjectRaster = arcpy.Raster(NO2_setNull_ProjectRaster)

        # Process: Raster Calculator (Raster Calculator) (ia)
        Pollution_combine_2021_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\Pollution_combine_2021.tif"
        Raster_Calculator = Pollution_combine_2021_tif
        Pollution_combine_2021_tif =  SO2_SetNull_ProjectRaster + NO2_setNull_ProjectRaster
        Pollution_combine_2021_tif.save(Raster_Calculator)


        # Process: Focal Statistics (Focal Statistics) (ia)
        Pol_combine_focal_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\proc\\Pol_combine_focal.tif"
        Focal_Statistics = Pol_combine_focal_tif
        Pol_combine_focal_tif = arcpy.ia.FocalStatistics(in_raster=Pollution_combine_2021_tif, neighborhood="Circle 50 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
        Pol_combine_focal_tif.save(Focal_Statistics)


        # Process: Extract by Mask (Extract by Mask) (sa)
        Air_pol_v01_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\Air_pol_v01.tif"
        Extract_by_Mask = Air_pol_v01_tif
        Air_pol_v01_tif = arcpy.sa.ExtractByMask(in_raster=Pol_combine_focal_tif, in_mask_data=grid_1km_v01_1_tif)
        Air_pol_v01_tif.save(Extract_by_Mask)


        # Process: Raster Calculator (4) (Raster Calculator) (ia)
        Air_pol_norm_v01_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\air_pol\\v01\\Air_pol_norm_v01.tif"
        Raster_Calculator_4_ = Air_pol_norm_v01_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\air_pol\v01\proc\air_pol\air_pol.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\air_pol\v01\proc\air_pol\air_pol.gdb"):
            Air_pol_norm_v01_tif =  (Air_pol_v01_tif - Air_pol_v01_tif.minimum)/( Air_pol_v01_tif.maximum- Air_pol_v01_tif.minimum)*100
            Air_pol_norm_v01_tif.save(Raster_Calculator_4_)


if __name__ == '__main__':
    air_pol_v1()
