# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-12-15 15:12:12
"""
import arcpy
from arcpy.ia import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    Gebco_2021_mosaic_dat = arcpy.Raster("Gebco_2021_mosaic.dat")
    grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
    Octocorals_merge_tif = arcpy.Raster("Octocorals_merge.tif")
    Gebco_2021_mosaic_mask_tif_2_ = arcpy.Raster("Gebco_2021_mosaic_mask.tif")

    # Process: Project Raster (Project Raster) (management)
    Gebco_2021_mosaic_ProjectRas = "C:\\Users\\piczer\\AppData\\Local\\Temp\\ArcGISProTemp22484\\60e2f685-3815-4d36-a40c-6c2abc0d676e\\Default.gdb\\Gebco_2021_mosaic_ProjectRas"
    arcpy.management.ProjectRaster(in_raster=Gebco_2021_mosaic_dat, out_raster=Gebco_2021_mosaic_ProjectRas, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="369,670078156418 369,670078156418", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
    Gebco_2021_mosaic_ProjectRas = arcpy.Raster(Gebco_2021_mosaic_ProjectRas)

    # Process: Extract by Mask (Extract by Mask) (sa)
    Gebco_2021_mosaic_mask_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\dbh_coral\\v01\\proc\\Gebco_2021_mosaic_mask.tif"
    Extract_by_Mask = Gebco_2021_mosaic_mask_tif
    Gebco_2021_mosaic_mask_tif = arcpy.sa.ExtractByMask(in_raster=Gebco_2021_mosaic_ProjectRas, in_mask_data=grid_1km_v01_1_tif)
    Gebco_2021_mosaic_mask_tif.save(Extract_by_Mask)


    # Process: Fill (Fill) (sa)
    Octocoral_merg_fill_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\dbh_coral\\v01\\proc\\Octocoral_merg_fill.tif"
    Fill = Octocoral_merg_fill_tif
    Octocoral_merg_fill_tif = arcpy.sa.Fill(in_surface_raster=Octocorals_merge_tif, z_limit=None)
    Octocoral_merg_fill_tif.save(Fill)


    # Process: Raster Calculator (Raster Calculator) (ia)
    Gebco_2021_mosaic_mask_below_photic_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\dbh_coral\\v01\\proc\\Gebco_2021_mosaic_mask_below_photic.tif"
    Raster_Calculator = Gebco_2021_mosaic_mask_below_photic_tif
    Gebco_2021_mosaic_mask_below_photic_tif =  Gebco_2021_mosaic_mask_tif_2_ <200
    Gebco_2021_mosaic_mask_below_photic_tif.save(Raster_Calculator)


    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    Cold_Octocoral_underphoticzone_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\dbh_coral\\v01\\proc\\Cold_Octocoral_underphoticzone.tif"
    Extract_by_Mask_2_ = Cold_Octocoral_underphoticzone_tif
    Cold_Octocoral_underphoticzone_tif = arcpy.sa.ExtractByMask(in_raster=Octocoral_merg_fill_tif, in_mask_data=Gebco_2021_mosaic_mask_below_photic_tif)
    Cold_Octocoral_underphoticzone_tif.save(Extract_by_Mask_2_)


    # Process: Project Raster (2) (Project Raster) (management)
    Cold_coral_v01_1km_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\dbh_coral\\v01\\Cold_coral_v01_1km.tif"
    arcpy.management.ProjectRaster(in_raster=Cold_Octocoral_underphoticzone_tif, out_raster=Cold_coral_v01_1km_tif, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", resampling_type="NEAREST", cell_size="1000 1000", geographic_transform=[], Registration_Point="", in_coor_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]", vertical="NO_VERTICAL")
    Cold_coral_v01_1km_tif = arcpy.Raster(Cold_coral_v01_1km_tif)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp22484\60e2f685-3815-4d36-a40c-6c2abc0d676e\Default.gdb", workspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp22484\60e2f685-3815-4d36-a40c-6c2abc0d676e\Default.gdb"):
        Model()
