# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-12 09:50:58
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def mariculture():  # mariculture

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    mariculture_3_ = "mariculture"
    Chl_a_norm_int_tif = arcpy.Raster("Chl_a_norm_int.tif")
    v1_flow_acc_pres_norm_int_tif = arcpy.Raster("v1_flow_acc_pres_norm_int.tif")
    mariculture_buffer10km_shp_mariculture_buffer10km = "ModelBuilder\\mariculture_buffer10km.shp:mariculture_buffer10km"
    grid_1km_v01_1_tif_2_ = arcpy.Raster("grid_1km_v01.1.tif")
    proc = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc"
    v01 = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01"
    proc_2_ = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc"
    aquaculture_eutro_relativ_tif_aquaculture_eutro_relativ_tif = arcpy.Raster("ModelBuilder\\aquaculture_eutro_relativ.tif:aquaculture_eutro_relativ.tif")

    # Process: Project (Project) (management)
    marine_culture_project_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\marine_culture_project.shp"
    arcpy.management.Project(in_dataset=mariculture_3_, out_dataset=marine_culture_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"WGS_1984_EASE-Grid_2.0_Global\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",30.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

    # Process: Buffer (Buffer) (analysis)
    mariculture_buffer10km_shp = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\mariculture_buffer10km.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]"):
        arcpy.analysis.Buffer(in_features=marine_culture_project_shp, out_feature_class=mariculture_buffer10km_shp, buffer_distance_or_field="10 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

    # Process: Weighted Sum (Weighted Sum) (ia)
    chla_alow_acc_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\chla_alow_acc.tif"
    Weighted_Sum = chla_alow_acc_tif
    chla_alow_acc_tif = arcpy.ia.WeightedSum(in_rasters=[[Chl_a_norm_int_tif, "Value", 6], [v1_flow_acc_pres_norm_int_tif, "Value", 4]])
    chla_alow_acc_tif.save(Weighted_Sum)


    # Process: Raster Calculator (Raster Calculator) (ia)
    chla_flow_acc_norm_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\chla_flow_acc_norm.tif"
    Raster_Calculator = chla_flow_acc_norm_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        chla_flow_acc_norm_tif =  ((chla_alow_acc_tif-chla_alow_acc_tif.minimum)/ (chla_alow_acc_tif.maximum - chla_alow_acc_tif.minimum))*100
        chla_flow_acc_norm_tif.save(Raster_Calculator)


    # Process: Polygon to Raster (Polygon to Raster) (conversion)
    mariculture_10km_buffer_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\mariculture_10km_buffer.tif"
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        arcpy.conversion.PolygonToRaster(in_features=mariculture_buffer10km_shp_mariculture_buffer10km, value_field="Id", out_rasterdataset=mariculture_10km_buffer_tif, cell_assignment="MAXIMUM_COMBINED_AREA", priority_field="Id", cellsize="M:\\marin\\swoc\\work\\wiosym\\data\\reg\\grid\\grid\\v01\\grid_1km_v01.1.tif", build_rat="BUILD")

    # Process: Extract by Mask (Extract by Mask) (sa)
    mariculture_eutro_relativ_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\mariculture_eutro_relativ.tif"
    Extract_by_Mask = mariculture_eutro_relativ_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        mariculture_eutro_relativ_tif = arcpy.sa.ExtractByMask(in_raster=chla_flow_acc_norm_tif, in_mask_data=mariculture_10km_buffer_tif)
        mariculture_eutro_relativ_tif.save(Extract_by_Mask)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    mariculture_eutro_relativ_1_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\mariculture_eutro_relativ_+1.tif"
    Raster_Calculator_2_ = mariculture_eutro_relativ_1_tif
    mariculture_eutro_relativ_1_tif =  mariculture_eutro_relativ_tif+1
    mariculture_eutro_relativ_1_tif.save(Raster_Calculator_2_)


    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    mariculture_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[mariculture_eutro_relativ_1_tif, grid_1km_v01_1_tif_2_], output_location=proc, raster_dataset_name_with_extension="mariculture_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    mariculture_combine_grid_tif = arcpy.Raster(mariculture_combine_grid_tif)

    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    mariculture_norm_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\mariculture_norm.tif"
    Raster_Calculator_3_ = mariculture_norm_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        mariculture_norm_tif =  ((mariculture_combine_grid_tif- mariculture_combine_grid_tif.minimum)/(mariculture_combine_grid_tif.maximum-mariculture_combine_grid_tif.minimum))*100
        mariculture_norm_tif.save(Raster_Calculator_3_)


    # Process: Raster Calculator (4) (Raster Calculator) (ia)
    grid0_tif = "\\\\sgu.se\\SGU\\prod\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\aquaculture_mariculture\\v01\\proc\\aquaculture\\grid0.tif"
    Raster_Calculator_4_ = grid0_tif
    with arcpy.EnvManager(cellSize=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        grid0_tif =  grid_1km_v01_1_tif_2_*0
        grid0_tif.save(Raster_Calculator_4_)


    # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
    mariculture_v2_tif = arcpy.management.MosaicToNewRaster(input_rasters=[mariculture_eutro_relativ_tif, grid0_tif], output_location=v01, raster_dataset_name_with_extension="mariculture_v2.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    mariculture_v2_tif = arcpy.Raster(mariculture_v2_tif)

    # Process: Mosaic To New Raster (3) (Mosaic To New Raster) (management)
    aquaculture_v2_tif = arcpy.management.MosaicToNewRaster(input_rasters=[grid0_tif, aquaculture_eutro_relativ_tif_aquaculture_eutro_relativ_tif], output_location=v01, raster_dataset_name_with_extension="aquaculture_v2.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    aquaculture_v2_tif = arcpy.Raster(aquaculture_v2_tif)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\aquaculture_mariculture\v01\proc\aquaculture\Default.gdb", workspace=r"\\sgu.se\SGU\prod\proj\marin\swoc\work\wiosym\data\reg\pres\aquaculture_mariculture\v01\proc\aquaculture\Default.gdb"):
        mariculture()
