# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-07 10:16:16
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def mudflat_model():  # mudflat_model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")

    Intertidal_areas2014_16_tif = arcpy.Raster("Intertidal_areas2014-16.tif")
    Intertidal_areas2011_13_tif = arcpy.Raster("Intertidal_areas2011-13.tif")
    Intertidal_areas2002_04_tif = arcpy.Raster("Intertidal_areas2002-04.tif")
    wio_codaMUD_idw3d_Proj_tif = arcpy.Raster("wio_codaMUD_idw3d_Proj.tif")
    Intertidal_2002_2016_setnull_tif_3_ = arcpy.Raster("Intertidal_2002-2016_setnull.tif")
    Intertidal_2002_2016_mudfalt_potential_tif_Intertidal_2002_2016_mudfalt_potential_tif = arcpy.Raster("ModelBuilder\\Intertidal_2002-2016_mudfalt_potential.tif:Intertidal_2002-2016_mudfalt_potential.tif")
    Intertidal_2002_2016_mudfalt_potential_log1_tif_Intertidal_2002_2016_mudfalt_potential_log1_tif = arcpy.Raster("ModelBuilder\\Intertidal_2002-2016_mudfalt_potential_log1.tif:Intertidal_2002-2016_mudfalt_potential_log1.tif")
    grid_1km_na_v01_1_tif = arcpy.Raster("grid_1km_na_v01.1.tif")

    # Process: Raster Calculator (Raster Calculator) (ia)
    Intertidal_2002_2016_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016.tif"
    Raster_Calculator = Intertidal_2002_2016_tif
    Intertidal_2002_2016_tif =  Intertidal_areas2014_16_tif + Intertidal_areas2011_13_tif + Intertidal_areas2002_04_tif
    Intertidal_2002_2016_tif.save(Raster_Calculator)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    Intertidal_2002_2016_setnull_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016.tif\\Intertidal_2002-2016_setnull.tif"
    Raster_Calculator_2_ = Intertidal_2002_2016_setnull_tif
    Intertidal_2002_2016_setnull_tif = SetNull(Intertidal_2002_2016_tif<1,Intertidal_2002_2016_tif)
    Intertidal_2002_2016_setnull_tif.save(Raster_Calculator_2_)


    # Process: Reclassify (Reclassify) (sa)
    Intertidal_2002_2016_setnull_reclassify_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016_setnull_reclassify.tif"
    Reclassify = Intertidal_2002_2016_setnull_reclassify_tif
    Intertidal_2002_2016_setnull_reclassify_tif = arcpy.sa.Reclassify(in_raster=Intertidal_2002_2016_setnull_tif_3_, reclass_field="Value", remap="1 1;2 1;3 1", missing_values="DATA")
    Intertidal_2002_2016_setnull_reclassify_tif.save(Reclassify)


    # Process: Extract by Mask (Extract by Mask) (sa)
    Intertidal_2002_2016_mudfalt_potential_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016_mudfalt_potential.tif"
    Extract_by_Mask = Intertidal_2002_2016_mudfalt_potential_tif
    Intertidal_2002_2016_mudfalt_potential_tif = arcpy.sa.ExtractByMask(in_raster=wio_codaMUD_idw3d_Proj_tif, in_mask_data=Intertidal_2002_2016_setnull_reclassify_tif)
    Intertidal_2002_2016_mudfalt_potential_tif.save(Extract_by_Mask)


    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    Intertidal_2002_2016_mudfalt_potential_log1_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016_mudfalt_potential_log1.tif"
    Raster_Calculator_3_ = Intertidal_2002_2016_mudfalt_potential_log1_tif
    Intertidal_2002_2016_mudfalt_potential_log1_tif =  Log10(Intertidal_2002_2016_mudfalt_potential_tif_Intertidal_2002_2016_mudfalt_potential_tif)
    Intertidal_2002_2016_mudfalt_potential_log1_tif.save(Raster_Calculator_3_)


    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    Intertidal_2002_2016_mudfalt_potential_log_1km_gd_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\ch_mudflat\\v01\\proc\\Intertidal_2002-2016_mudfalt_potential_log_1km_gd.tif"
    Extract_by_Mask_2_ = Intertidal_2002_2016_mudfalt_potential_log_1km_gd_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_na_v01.1.tif"):
        Intertidal_2002_2016_mudfalt_potential_log_1km_gd_tif = arcpy.sa.ExtractByMask(in_raster=Intertidal_2002_2016_mudfalt_potential_log1_tif_Intertidal_2002_2016_mudfalt_potential_log1_tif, in_mask_data=grid_1km_na_v01_1_tif)
        Intertidal_2002_2016_mudfalt_potential_log_1km_gd_tif.save(Extract_by_Mask_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\sgu.se\sgu\prod\proj\marin\swoc\work\wiosym\data\reg\eco\ch_mudflat\v01\proc\mudflat\Default.gdb", workspace=r"\\sgu.se\sgu\prod\proj\marin\swoc\work\wiosym\data\reg\eco\ch_mudflat\v01\proc\mudflat\Default.gdb"):
        mudflat_model()
