# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-07-01 11:13:25
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *

def macro_alg():  # macro_alg

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    macro_algae = "macro_algae"
    grid_1km_v01_1_tif = arcpy.Raster("ModelBuilder\\grid_1km_v01.1.tif")
    proc = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\proc"

    # Process: Project (Project) (management)
    macro_alg_project_shp = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\proc\\macro_alg_project.shp"
    arcpy.management.Project(in_dataset=macro_algae, out_dataset=macro_alg_project_shp, out_coor_system="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", transform_method=[], in_coor_system="PROJCS[\"World_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",0.0],PARAMETER[\"Standard_Parallel_1\",0.0],UNIT[\"Meter\",1.0]]", preserve_shape="NO_PRESERVE_SHAPE", max_deviation="", vertical="NO_VERTICAL")

    # Process: Point to Raster (Point to Raster) (conversion)
    macro_alg_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\proc\\macro_alg.tif"
    with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        arcpy.conversion.PointToRaster(in_features=macro_alg_project_shp, value_field="value", out_rasterdataset=macro_alg_tif, cell_assignment="MOST_FREQUENT", priority_field="NONE", cellsize="4800", build_rat="BUILD")

    # Process: Focal Statistics (Focal Statistics) (ia)
    macro_alg_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\proc\\macro_alg_focal.tif"
    Focal_Statistics = macro_alg_focal_tif
    with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        macro_alg_focal_tif = arcpy.ia.FocalStatistics(in_raster=macro_alg_tif, neighborhood="Wedge 3 0 360 CELL", statistics_type="MEDIAN", ignore_nodata="DATA", percentile_value=90)
        macro_alg_focal_tif.save(Focal_Statistics)


    # Process: Raster Calculator (Raster Calculator) (sa)
    macro_alg_1_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\proc\\macro_alg+1.tif"
    Raster_Calculator = macro_alg_1_tif
    macro_alg_1_tif =  macro_alg_focal_tif +1
    macro_alg_1_tif.save(Raster_Calculator)


    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    macro_alg_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[macro_alg_1_tif, grid_1km_v01_1_tif], output_location=proc, raster_dataset_name_with_extension="macro_alg_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
    macro_alg_combine_grid_tif = arcpy.Raster(macro_alg_combine_grid_tif)

    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    macro_algae_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\eco\\macro_alg\\v01\\macro_algae_norm.tif"
    Raster_Calculator_2_ = macro_algae_norm_tif
    with arcpy.EnvManager(cellSize=r"M:\proj\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        macro_algae_norm_tif =  ((macro_alg_combine_grid_tif- macro_alg_combine_grid_tif.minimum)/( macro_alg_combine_grid_tif.maximum-macro_alg_combine_grid_tif.minimum))*100
        macro_algae_norm_tif.save(Raster_Calculator_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\eco\macro_alg\v01\proc\macroalgae\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\eco\macro_alg\v01\proc\macroalgae\Default.gdb"):
        macro_alg()
