# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-08 02:26:23
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def pol_org():  # pol_org

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb"):
        TSIP_organic_toxin = "TSIP_organic_toxin"
        gebco_land_shallow_flow_accumulation_log10_n_tif = arcpy.Raster("gebco_land_shallow_flow_accumulation_log10_n.tif")
        proc = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc"
        grid_1km_v01_1_tif = arcpy.Raster("ModelBuilder\\grid_1km_v01.1.tif")
        grid_1km_v01_1_tif_2_ = arcpy.Raster("ModelBuilder\\grid_1km_v01.1.tif")
        v2_aug = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\v2_aug"

        # Process: Point to Raster (Point to Raster) (conversion)
        TSIP_organic_toxin_PointToRaster1 = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\Default.gdb\\TSIP_organic_toxin_PointToRaster1"
        with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb"):
            arcpy.conversion.PointToRaster(in_features=TSIP_organic_toxin, value_field="bs_scale", out_rasterdataset=TSIP_organic_toxin_PointToRaster1, cell_assignment="MOST_FREQUENT", priority_field="NONE", cellsize="20000", build_rat="BUILD")

        # Process: Raster Calculator (Raster Calculator) (ia)
        TSIP_organic_range_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\TSIP_organic_range.tif"
        Raster_Calculator = TSIP_organic_range_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb", 
                              snapRaster="grid_1km_v01.1.tif", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb"):
            TSIP_organic_range_tif =  TSIP_organic_toxin_PointToRaster1 +10
            TSIP_organic_range_tif.save(Raster_Calculator)


        # Process: Focal Flow (Focal Flow) (sa)
        flow_acc_focal_flow_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\flow_acc_focal_flow.tif"
        Focal_Flow = flow_acc_focal_flow_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            flow_acc_focal_flow_tif = arcpy.sa.FocalFlow(in_surface_raster=gebco_land_shallow_flow_accumulation_log10_n_tif, threshold_value=1)
            flow_acc_focal_flow_tif.save(Focal_Flow)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        flow_acc_mosiac_organic_tif = arcpy.management.MosaicToNewRaster(input_rasters=[TSIP_organic_range_tif, flow_acc_focal_flow_tif], output_location=proc, raster_dataset_name_with_extension="flow_acc_mosiac_organic.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
        flow_acc_mosiac_organic_tif = arcpy.Raster(flow_acc_mosiac_organic_tif)

        # Process: Focal Statistics (Focal Statistics) (ia)
        flow_acc_mosiac_organic_focal1_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\flow_acc_mosiac_organic_focal1.tif"
        Focal_Statistics = flow_acc_mosiac_organic_focal1_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
            flow_acc_mosiac_organic_focal1_tif = arcpy.ia.FocalStatistics(in_raster=flow_acc_mosiac_organic_tif, neighborhood="Wedge 10 0 360 CELL", statistics_type="SUM", ignore_nodata="NODATA", percentile_value=70)
            flow_acc_mosiac_organic_focal1_tif.save(Focal_Statistics)


        # Process: Extract by Mask (Extract by Mask) (sa)
        flow_acc_mosiac_organic_focal_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\flow_acc_mosiac_organic_focal.tif"
        Extract_by_Mask = flow_acc_mosiac_organic_focal_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            flow_acc_mosiac_organic_focal_tif = arcpy.sa.ExtractByMask(in_raster=flow_acc_mosiac_organic_focal1_tif, in_mask_data=grid_1km_v01_1_tif)
            flow_acc_mosiac_organic_focal_tif.save(Extract_by_Mask)


        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        pol_organic_norm_v_01_0_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\pol_organic_norm_v.01.0.tif"
        Raster_Calculator_2_ = pol_organic_norm_v_01_0_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster="grid_1km_v01.1.tif"):
            pol_organic_norm_v_01_0_tif =  ((flow_acc_mosiac_organic_focal_tif-flow_acc_mosiac_organic_focal_tif.minimum)/(flow_acc_mosiac_organic_focal_tif.maximum- flow_acc_mosiac_organic_focal_tif.minimum))*100
            pol_organic_norm_v_01_0_tif.save(Raster_Calculator_2_)


        # Process: Buffer (Buffer) (analysis)
        organic_buffer_shp = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\v2_aug\\organic_buffer.shp"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\pres\pol_org\v01\proc\pol_org\Default.gdb"):
            arcpy.analysis.Buffer(in_features=TSIP_organic_toxin, out_feature_class=organic_buffer_shp, buffer_distance_or_field="20 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="ALL", dissolve_field=[], method="PLANAR")

        # Process: Polygon to Raster (Polygon to Raster) (conversion)
        organicpol_buffer_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\v2_aug\\organicpol_buffer.tif"
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            arcpy.conversion.PolygonToRaster(in_features=organic_buffer_shp, value_field="FID", out_rasterdataset=organicpol_buffer_tif, cell_assignment="CELL_CENTER", priority_field="NONE", cellsize="M:\\marin\\swoc\\work\\wiosym\\data\\reg\\grid\\grid\\v01\\grid_1km_v01.1.tif", build_rat="BUILD")

        # Process: Focal Statistics (2) (Focal Statistics) (ia)
        organic_focal_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\v2_aug\\organic_focal.tif"
        Focal_Statistics_2_ = organic_focal_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            organic_focal_tif = arcpy.ia.FocalStatistics(in_raster=organicpol_buffer_tif, neighborhood="Circle 5 CELL", statistics_type="VARIETY", ignore_nodata="DATA", percentile_value=90)
            organic_focal_tif.save(Focal_Statistics_2_)


        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        grid_0proxy_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\proc\\pol_org\\v2_aug\\grid_0proxy.tif"
        Raster_Calculator_3_ = grid_0proxy_tif
        with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", mask=r"ModelBuilder\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                              snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            grid_0proxy_tif =  grid_1km_v01_1_tif_2_ *0
            grid_0proxy_tif.save(Raster_Calculator_3_)


        # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
        organic_pol_v2_tif = arcpy.management.MosaicToNewRaster(input_rasters=[organic_focal_tif, grid_0proxy_tif], output_location=v2_aug, raster_dataset_name_with_extension="organic_pol_v2.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
        organic_pol_v2_tif = arcpy.Raster(organic_pol_v2_tif)

        # Process: Resample (Resample) (management)
        pol_organic_v2_1km_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\pol_org\\v01\\pol_organic__v2_1km.tif"
        with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
            arcpy.management.Resample(in_raster=organic_pol_v2_tif, out_raster=pol_organic_v2_1km_tif, cell_size="1000 1000", resampling_type="NEAREST")
            pol_organic_v2_1km_tif = arcpy.Raster(pol_organic_v2_1km_tif)

if __name__ == '__main__':
    pol_org()
