# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-13 23:52:41
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *

def nutrient_inputv2():  # nutrient_inputv2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    nutrient_input_v02_1km_tif = arcpy.Raster("nutrient_input_v02_1km.tif")
    flow_pressure_v2_tif = arcpy.Raster("flow_pressure_v2.tif")

    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    flow_press_norm_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v02\\proc\\flow_press_norm.tif"
    Raster_Calculator_2_ = flow_press_norm_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        flow_press_norm_tif = (flow_pressure_v2_tif- flow_pressure_v2_tif.minimum)/(flow_pressure_v2_tif.maximum-flow_pressure_v2_tif.minimum)*100
        flow_press_norm_tif.save(Raster_Calculator_2_)


    # Process: Raster Calculator (Raster Calculator) (sa)
    nutrient_input_flow_pres_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v02\\proc\\nutrient_input_flow_pres.tif"
    Raster_Calculator = nutrient_input_flow_pres_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        nutrient_input_flow_pres_tif =  nutrient_input_v02_1km_tif * flow_press_norm_tif
        nutrient_input_flow_pres_tif.save(Raster_Calculator)


    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    Nutrient_input_v2_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\pres\\nutrient_input\\v02\\Nutrient_input_v2.tif"
    Raster_Calculator_3_ = Nutrient_input_v2_tif
    with arcpy.EnvManager(cellSize="grid_1km_v01.1.tif", mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", 
                          snapRaster="grid_1km_v01.1.tif"):
        Nutrient_input_v2_tif =  SquareRoot(nutrient_input_flow_pres_tif)
        Nutrient_input_v2_tif.save(Raster_Calculator_3_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp40932\8489a01e-658d-4bd2-b86c-4a19a1bb2375\Default.gdb", workspace=r"C:\Users\piczer\AppData\Local\Temp\ArcGISProTemp40932\8489a01e-658d-4bd2-b86c-4a19a1bb2375\Default.gdb"):
        nutrient_inputv2()
