# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-09-07 23:35:49
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *

def runoff_volumn():  # runoff_volumn

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    WIO_precipitation_mean_mm_tif = arcpy.Raster("WIO_precipitation_mean_mm.tif")
    shore_line_land_intertidal_mask_tif_shore_line_land_intertidal_mask_tif = arcpy.Raster("ModelBuilder\\shore_line_land_intertidal_mask.tif:shore_line_land_intertidal_mask.tif")
    GCN250_ARCII_average_tif = arcpy.Raster("GCN250_ARCII_average.tif")
    DEM_land_shoreline_fill_flow_acc_tif_DEM_land_shoreline_fill_flow_acc_tif_3_ = arcpy.Raster("ModelBuilder\\DEM_land_shoreline_fill_flow_acc.tif:DEM_land_shoreline_fill_flow_acc.tif")
    DEM_land_shoreline_fill_tif_DEM_land_shoreline_fill_tif = arcpy.Raster("ModelBuilder\\DEM_land_shoreline_fill.tif:DEM_land_shoreline_fill.tif")
    DEM_land_shoreline_fill_flow_direction_tif_DEM_land_shoreline_fill_flow_direction_tif = arcpy.Raster("ModelBuilder\\DEM_land_shoreline_fill_flow_direction.tif:DEM_land_shoreline_fill_flow_direction.tif")

    # Process: Extract by Mask (2) (Extract by Mask) (sa)
    precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\runoff_volumn\\precipitation_2007-2018yearlyavr_mm_clip_land_intertidal_extend.tif"
    Extract_by_Mask_2_ = precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif = arcpy.sa.ExtractByMask(in_raster=WIO_precipitation_mean_mm_tif, in_mask_data=shore_line_land_intertidal_mask_tif_shore_line_land_intertidal_mask_tif)
        precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif.save(Extract_by_Mask_2_)


    # Process: Extract by Mask (Extract by Mask) (sa)
    CN_clip_land_intertidal_extend_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\runoff_volumn\\CN_clip_land_intertidal_extend.tif"
    Extract_by_Mask = CN_clip_land_intertidal_extend_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        CN_clip_land_intertidal_extend_tif = arcpy.sa.ExtractByMask(in_raster=GCN250_ARCII_average_tif, in_mask_data=shore_line_land_intertidal_mask_tif_shore_line_land_intertidal_mask_tif)
        CN_clip_land_intertidal_extend_tif.save(Extract_by_Mask)


    # Process: Raster Calculator (Raster Calculator) (ia)
    S_potential_retention_max_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\runoff_volumn\\S_potential_retention(max).tif"
    Raster_Calculator = S_potential_retention_max_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        S_potential_retention_max_tif =  (1000/CN_clip_land_intertidal_extend_tif)-10
        S_potential_retention_max_tif.save(Raster_Calculator)


    # Process: Raster Calculator (2) (Raster Calculator) (ia)
    I_initial_abtraction_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\runoff_volumn\\I_initial_abtraction.tif"
    Raster_Calculator_2_ = I_initial_abtraction_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster=r"ModelBuilder\grid_1km_v01.1.tif"):
        I_initial_abtraction_tif =  S_potential_retention_max_tif *0.2
        I_initial_abtraction_tif.save(Raster_Calculator_2_)


    # Process: Raster Calculator (3) (Raster Calculator) (ia)
    Q1_runoff_volumn_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\runoff_volumn\\Q1_runoff_volumn.tif"
    Raster_Calculator_3_ = Q1_runoff_volumn_tif
    Q1_runoff_volumn_tif = ((precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif - I_initial_abtraction_tif)*(precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif-I_initial_abtraction_tif))/ (precipitation_2007_2018yearlyavr_mm_clip_land_intertidal_extend_tif-I_initial_abtraction_tif)+ S_potential_retention_max_tif
    Q1_runoff_volumn_tif.save(Raster_Calculator_3_)


    # Process: Flow Distance (Flow Distance) (sa)
    flow_distance_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\flow_distance.tif"
    Flow_Distance = flow_distance_tif
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        flow_distance_tif = arcpy.sa.FlowDistance(in_stream_raster=DEM_land_shoreline_fill_flow_acc_tif_DEM_land_shoreline_fill_flow_acc_tif_3_, in_surface_raster=DEM_land_shoreline_fill_tif_DEM_land_shoreline_fill_tif, in_flow_direction_raster=DEM_land_shoreline_fill_flow_direction_tif_DEM_land_shoreline_fill_flow_direction_tif, distance_type="VERTICAL", flow_direction_type="D8", statistics_type="MAXIMUM")
        flow_distance_tif.save(Flow_Distance)


    # Process: Raster Calculator (4) (Raster Calculator) (ia)
    flow_distance_setn_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\env\\hydro\\v01\\proc\\hydro_aug2022_update\\flow_distance_setn.tif"
    Raster_Calculator_4_ = flow_distance_setn_tif
    with arcpy.EnvManager(cellSize=r"M:\marin\swoc\work\wiosym\data\reg\grid\grid\v01\grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        flow_distance_setn_tif =  SetNull(flow_distance_tif<500, flow_distance_tif)
        flow_distance_setn_tif.save(Raster_Calculator_4_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\env\hydro\v01\proc\hydro_aug2022_update\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\env\hydro\v01\proc\hydro_aug2022_update\Default.gdb"):
        runoff_volumn()
