# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-19 09:51:45
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *

def ship_underwaternoise():  # ship_underwaternoise

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
        ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif = arcpy.Raster("ModelBuilder\\ship_commer_mask.tif:ship_commer_mask.tif:ship_commer_mask.tif:ship_commer_mask.tif:ship_commer_mask.tif:ship_commer_mask.tif")
        grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
        proc = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc"

        # Process: Raster Calculator (Raster Calculator) (ia)
        commer_log10_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\commer_log10.tif"
        Raster_Calculator = commer_log10_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
            commer_log10_tif =  Log10(ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif_ship_commer_mask_tif)
            commer_log10_tif.save(Raster_Calculator)


        # Process: Focal Statistics (Focal Statistics) (ia)
        commer_boating_focal_under_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\commer_boating_focal_under.tif"
        Focal_Statistics = commer_boating_focal_under_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
            commer_boating_focal_under_tif = arcpy.ia.FocalStatistics(in_raster=commer_log10_tif, neighborhood="Wedge 10 0 90 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=90)
            commer_boating_focal_under_tif.save(Focal_Statistics)


        # Process: Extract by Mask (Extract by Mask) (sa)
        commer_extract_mask_focal_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\commer_extract_mask_focal.tif"
        Extract_by_Mask = commer_extract_mask_focal_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
            commer_extract_mask_focal_tif = arcpy.sa.ExtractByMask(in_raster=commer_boating_focal_under_tif, in_mask_data=grid_1km_v01_1_tif)
            commer_extract_mask_focal_tif.save(Extract_by_Mask)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS", scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
            commer_combinr_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[commer_extract_mask_focal_tif, grid_1km_v01_1_tif], output_location=proc, raster_dataset_name_with_extension="commer_combinr_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="REJECT")[0]
            commer_combinr_grid_tif = arcpy.Raster(commer_combinr_grid_tif)

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        underwaternoise_norm_v01_1_tif = "M:\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\underwaternoise_norm_v01.1.tif"
        Raster_Calculator_2_ = underwaternoise_norm_v01_1_tif
        with arcpy.EnvManager(scratchWorkspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
            underwaternoise_norm_v01_1_tif =  ((commer_combinr_grid_tif - commer_combinr_grid_tif.minimum)/(commer_combinr_grid_tif.maximum-commer_combinr_grid_tif.minimum))*100
            underwaternoise_norm_v01_1_tif.save(Raster_Calculator_2_)


if __name__ == '__main__':
    ship_underwaternoise()
