# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-06-18 16:17:07
"""
import arcpy
from arcpy.ia import *
from arcpy.sa import *

def ship_recreational_boating():  # ship_recreational_boating

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    ship_leisure_mask_tif_ship_leisure_mask_tif = arcpy.Raster("ModelBuilder\\ship_leisure_mask.tif:ship_leisure_mask.tif")
    grid_1km_v01_1_tif = arcpy.Raster("grid_1km_v01.1.tif")
    proc = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc"

    # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
    with arcpy.EnvManager(pyramid="PYRAMIDS -1 NEAREST LZ77 75 NO_SKIP NO_SIPS"):
        leisure_boat_combine_grid_tif = arcpy.management.MosaicToNewRaster(input_rasters=[ship_leisure_mask_tif_ship_leisure_mask_tif, grid_1km_v01_1_tif], output_location=proc, raster_dataset_name_with_extension="leisure_boat_combine_grid.tif", coordinate_system_for_the_raster="PROJCS[\"WGS_1984_Cylindrical_Equal_Area\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Cylindrical_Equal_Area\"],PARAMETER[\"false_easting\",0.0],PARAMETER[\"false_northing\",0.0],PARAMETER[\"central_meridian\",12.0],PARAMETER[\"standard_parallel_1\",-12.0],UNIT[\"Meter\",1.0]]", pixel_type="32_BIT_FLOAT", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
        leisure_boat_combine_grid_tif = arcpy.Raster(leisure_boat_combine_grid_tif)

    # Process: Raster Calculator (Raster Calculator) (ia)
    leisure_log_transform_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\leisure_log_transform.tif"
    Raster_Calculator = leisure_log_transform_tif
    leisure_log_transform_tif = Log10(leisure_boat_combine_grid_tif)
    leisure_log_transform_tif.save(Raster_Calculator)


    # Process: Focal Statistics (Focal Statistics) (ia)
    recreational_boating_focal_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\recreational_boating_focal.tif"
    Focal_Statistics = recreational_boating_focal_tif
    recreational_boating_focal_tif = arcpy.ia.FocalStatistics(in_raster=leisure_log_transform_tif, neighborhood="Wedge 10 0 360 CELL", statistics_type="SUM", ignore_nodata="DATA", percentile_value=80)
    recreational_boating_focal_tif.save(Focal_Statistics)


    # Process: Extract by Mask (7) (Extract by Mask) (sa)
    recreational_boating_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\proc\\recreational_boating.tif"
    Extract_by_Mask_7_ = recreational_boating_tif
    with arcpy.EnvManager(mask="grid_1km_v01.1.tif", outputCoordinateSystem="PROJCS["WGS_1984_Cylindrical_Equal_Area",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Cylindrical_Equal_Area"],PARAMETER["false_easting",0.0],PARAMETER["false_northing",0.0],PARAMETER["central_meridian",12.0],PARAMETER["standard_parallel_1",-12.0],UNIT["Meter",1.0]]", snapRaster="grid_1km_v01.1.tif"):
        recreational_boating_tif = arcpy.sa.ExtractByMask(in_raster=recreational_boating_focal_tif, in_mask_data=grid_1km_v01_1_tif)
        recreational_boating_tif.save(Extract_by_Mask_7_)


    # Process: Raster Calculator (2) (Raster Calculator) (sa)
    recreational_boating_norm_1km_v01_1_tif = "M:\\proj\\marin\\swoc\\work\\wiosym\\data\\reg\\act\\ship\\v01\\recreational_boating_norm_1km_v01.1.tif"
    Raster_Calculator_2_ = recreational_boating_norm_1km_v01_1_tif
    recreational_boating_norm_1km_v01_1_tif =  ((recreational_boating_tif -recreational_boating_tif.minimum)/(recreational_boating_tif.maximum- recreational_boating_tif.minimum))*100
    recreational_boating_norm_1km_v01_1_tif.save(Raster_Calculator_2_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb", workspace=r"M:\proj\marin\swoc\work\wiosym\data\reg\act\ship\v01\proc\ship\Default.gdb"):
        ship_recreational_boating()
